In [36]:
%load_ext autoreload
%autoreload 2

In [37]:
import numpy as np
import polars as pl
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV, cross_validate, cross_val_predict, train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, roc_auc_score, make_scorer

import seaborn as sn
import matplotlib.pyplot as plt

In [2]:
# read tsv clinical matrix
clinicalMatrix = pd.read_csv("brca_data/TCGA.BRCA.sampleMap-BRCA_clinicalMatrix.tsv", sep="\t")

In [2]:
file_path = 'MOGLAM/BRCA_split/BRCA/1_featname.csv'  # Replace 'your_file.txt' with the actual file path

# Open the file and read lines into a list
with open(file_path, 'r') as file:
    file_content = file.readlines()

# Optionally, strip newline characters from each line
gene_list = [line.strip().split('|')[0] for line in file_content][1:]

# Now, file_content is a list where each element corresponds to a line in the file
print(gene_list)

['A2ML1', 'ABAT', 'ABCA13', 'ABCC11', 'ABCC8', 'ABCG1', 'ABCG2', 'ABLIM3', 'ABTB2', 'ACADSB', 'ACE2', 'ACOT4', 'ACOX2', 'ACTL6A', 'ACTR3B', 'ACVR1B', 'ADAMTS15', 'ADCY9', 'ADD1', 'AFF3', 'AGR2', 'AGR3', 'AKR1E2', 'AKR7A3', 'ALAD', 'AMD1', 'AMY1A', 'ANKLE1', 'ANKMY1', 'ANKRA2', 'ANKRD30A', 'ANKRD30B', 'ANKRD42', 'ANKRD45', 'ANKS6', 'ANLN', 'ANP32E', 'ANXA8L2', 'ANXA9', 'APBB2', 'APH1B', 'APPL2', 'ARHGAP11A', 'ARHGEF4', 'ARL9', 'ARSG', 'ART3', 'AR', 'ASNS', 'ASTN2', 'ATAD2', 'ATL2', 'ATOH7', 'ATP1B3', 'ATP5C1', 'ATP6V1C2', 'ATP7B', 'ATP8B1', 'AURKA', 'AURKB', 'B3GNT4', 'B3GNT5', 'BAIAP2L2', 'BBOX1', 'BBS1', 'BBS4', 'BBS5', 'BCAM', 'BCAS1', 'BCL11A', 'BCL2', 'BECN1', 'BHLHE40', 'BIRC5', 'BLM', 'BPI', 'BRIX1', 'BTG2', 'BTG3', 'BUB1', 'BYSL', 'C10orf116', 'C10orf26', 'C10orf32', 'C10orf90', 'C11orf75', 'C11orf82', 'C11orf86', 'C12orf11', 'C12orf48', 'C12orf72', 'C13orf27', 'C14orf174', 'C14orf45', 'C15orf23', 'C15orf42', 'C16orf45', 'C16orf57', 'C16orf61', 'C16orf71', 'C17orf28', 'C19orf51', 'C1QL2', 'C1QL4', 'C1orf106', 'C1orf112', 'C1orf135', 'C1orf64', 'C20orf114', 'C20orf26', 'C22orf23', 'C2orf40', 'C2orf55', 'C2orf71', 'C3orf26', 'C4orf32', 'C4orf34', 'C5orf30', 'C5orf36', 'C5orf53', 'C6orf153', 'C6orf15', 'C6orf211', 'C6orf218', 'C6orf97', 'C7orf63', 'C8orf47', 'C8orf76', 'C9orf100', 'C9orf116', 'C9orf152', 'C9orf170', 'C9orf30', 'C9orf40', 'C9orf53', 'C9orf64', 'C9orf98', 'CA12', 'CA6', 'CA9', 'CACNA2D2', 'CACYBP', 'CALCOCO1', 'CAMKV', 'CAPN11', 'CAPN13', 'CAPN8', 'CASC1', 'CBX2', 'CBX7', 'CCDC125', 'CCDC129', 'CCDC150', 'CCDC30', 'CCDC48', 'CCDC74B', 'CCDC77', 'CCDC82', 'CCDC96', 'CCDC99', 'CCKBR', 'CCNA2', 'CCNB1', 'CCNB2', 'CCNDBP1', 'CCNE1', 'CCNG2', 'CCT4', 'CCT5', 'CCT6A', 'CDC123', 'CDC20', 'CDC25A', 'CDC25B', 'CDC45', 'CDC6', 'CDC7', 'CDCA2', 'CDCA3', 'CDCA5', 'CDCA7', 'CDCA8', 'CDK1', 'CDK2AP1', 'CDKN2A', 'CDKN3', 'CEBPB', 'CENPA', 'CENPE', 'CENPF', 'CENPL', 'CENPN', 'CENPO', 'CENPW', 'CEP55', 'CGRRF1', 'CHAC2', 'CHAD', 'CHAF1B', 'CHEK1', 'CHEK2', 'CHODL', 'CHRD', 'CHRM3', 'CHRNA5', 'CHST2', 'CHST3', 'CIRBP', 'CIRH1A', 'CKS1B', 'CKS2', 'CLCN4', 'CLDN11', 'CLDN19', 'CLSTN2', 'CMBL', 'CMTM7', 'CMYA5', 'CNGA1', 'CNGB1', 'CNN1', 'CNTNAP3', 'COG2', 'COL11A2', 'COL22A1', 'COQ7', 'CPA4', 'CPEB2', 'CPLX1', 'CPSF3', 'CRHR1', 'CRIP1', 'CROT', 'CRY2', 'CSDA', 'CSRP2', 'CSTB', 'CT62', 'CTPS', 'CX3CL1', 'CXCL1', 'CXCL3', 'CXCL5', 'CXXC5', 'CXorf49B', 'CXorf61', 'CYB5D2', 'CYB5R1', 'CYBRD1', 'CYP27C1', 'CYP2B7P1', 'CYP39A1', 'CYP4B1', 'CYP4Z2P', 'DACH1', 'DALRD3', 'DAZAP2', 'DBF4', 'DCAF13', 'DDN', 'DEGS2', 'DEK', 'DEPDC1B', 'DEPDC1', 'DIAPH3', 'DKC1', 'DLX6AS', 'DLX6', 'DMRT1', 'DMRTA2', 'DNAH7', 'DNAJB11', 'DNAJC12', 'DNAJC2', 'DNAJC9', 'DNAL1', 'DNALI1', 'DNER', 'DNMBP', 'DNMT3B', 'DONSON', 'DSC2', 'DSC3', 'DSCC1', 'DSG1', 'DSN1', 'DUSP7', 'DUSP9', 'DYNLRB2', 'E2F1', 'E2F2', 'E2F3', 'EAPP', 'ECE2', 'EDA2R', 'EFCAB6', 'EIF2C2', 'EIF2S2', 'EME1', 'EN1', 'ENO1', 'ENPP1', 'ENY2', 'EPB41L4A', 'EPHB1', 'EPHB6', 'ERBB4', 'ERGIC1', 'ESR1', 'ESYT3', 'EVL', 'EXO1', 'EXOC6', 'EZH2', 'F7', 'FAAH', 'FABP7', 'FAF1', 'FAM114A2', 'FAM120AOS', 'FAM123B', 'FAM134B', 'FAM136A', 'FAM150B', 'FAM161B', 'FAM171A1', 'FAM174A', 'FAM174B', 'FAM179B', 'FAM198B', 'FAM19A3', 'FAM19A4', 'FAM47E', 'FAM54A', 'FAM63A', 'FAM64A', 'FAM72A', 'FAM72B', 'FAM72D', 'FAM83D', 'FANCA', 'FANCB', 'FANCE', 'FAT2', 'FBN3', 'FBP1', 'FBXL17', 'FBXL5', 'FBXO36', 'FEN1', 'FERMT1', 'FGD3', 'FGFBP1', 'FLAD1', 'FLJ36031', 'FLJ45983', 'FMO5', 'FMO6P', 'FNIP1', 'FOXA1', 'FOXC1', 'FOXM1', 'FOXP1', 'FRY', 'FSCN1', 'FSD1', 'FSIP1', 'FUT8', 'FZD9', 'GABBR2', 'GABRA5', 'GABRP', 'GALNT10', 'GAL', 'GAMT', 'GARS', 'GART', 'GATA3', 'GDF5', 'GFRA1', 'GFRA3', 'GGH', 'GIN1', 'GINS1', 'GINS3', 'GINS4', 'GJB3', 'GLI3', 'GLIPR1L2', 'GLT25D1', 'GMPR2', 'GMPS', 'GOLGA1', 'GP2', 'GPD1L', 'GPIHBP1', 'GPM6B', 'GPN1', 'GPR12', 'GPR156', 'GPR160', 'GPR161', 'GPR77', 'GPR81', 'GPRASP1', 'GPSM2', 'GREB1', 'GRM6', 'GRPR', 'GSG2', 'GSTP1', 'GTPBP4', 'GTPBP8', 'GTSE1', 'H2AFZ', 'HAPLN3', 'HDAC2', 'HDGF', 'HEXIM1', 'HHAT', 'HIST1H2AH', 'HJURP', 'HMGA1', 'HORMAD1', 'HPDL', 'HRCT1', 'HRK', 'HSD17B4', 'HSPA14', 'IFFO2', 'IFRD1', 'IFT140', 'IGBP1', 'IGF1R', 'IGF2BP2', 'IGF2BP3', 'IGFALS', 'IGFBP4', 'IL12RB2', 'IL34', 'ILF2', 'IMPA2', 'INA', 'INGX', 'INPP4B', 'INPP5J', 'IRS1', 'IRX1', 'ISL2', 'ITPR1', 'IVD', 'JKAMP', 'KARS', 'KCMF1', 'KCNG1', 'KCNH1', 'KCNJ11', 'KCNK15', 'KCNK5', 'KCNQ4', 'KCNS1', 'KCTD3', 'KCTD6', 'KDM4B', 'KIAA0020', 'KIAA0040', 'KIAA0141', 'KIAA0232', 'KIAA1370', 'KIAA1407', 'KIAA1467', 'KIAA1524', 'KIAA1609', 'KIF11', 'KIF13B', 'KIF14', 'KIF15', 'KIF16B', 'KIF18A', 'KIF18B', 'KIF20A', 'KIF23', 'KIF2C', 'KIF4A', 'KIF4B', 'KIFC1', 'KLHDC1', 'KLHDC2', 'KLHDC7A', 'KLHDC9', 'KLHL29', 'KLK6', 'KLK7', 'KLK8', 'KPNA2', 'KRT16', 'KRT6B', 'KRT6C', 'KRT83', 'KRT9', 'L3MBTL4', 'LANCL3', 'LBR', 'LCMT2', 'LCTL', 'LDHB', 'LEMD1', 'LEPREL1', 'LIMA1', 'LIN28B', 'LMO4', 'LMOD1', 'LMX1B', 'LOC100127888', 'LOC100128977', 'LOC100130148', 'LOC100190939', 'LOC145837', 'LOC284578', 'LOC285629', 'LOC728264', 'LOC84740', 'LOC84856', 'LONRF2', 'LPIN1', 'LPO', 'LRBA', 'LRIG1', 'LRP8', 'LRRC46', 'LRRC48', 'LRRC50', 'LRTOMT', 'LY6D', 'LYAR', 'MAB21L1', 'MAD2L1', 'MAGEB4', 'MAGED2', 'MAGOH', 'MAG', 'MAMDC2', 'MAML3', 'MAN2B2', 'MAP2', 'MAP3K12', 'MAPK4', 'MAPT', 'MASTL', 'MATN4', 'MCCC2', 'MCM10', 'MCM2', 'MCM3', 'MCM4', 'MCM6', 'MCM7', 'MDGA2', 'MED30', 'MEIS3P1', 'MELK', 'MEMO1', 'MFGE8', 'MFI2', 'MGC3771', 'MIA', 'MICALL1', 'MID1', 'MKL2', 'MLPH', 'MND1', 'MOAP1', 'MOBKL2B', 'MPHOSPH6', 'MPP6', 'MPP7', 'MRPL15', 'MRPL37', 'MRPL47', 'MSH6', 'MSL3', 'MSLN', 'MTERFD1', 'MTHFD1L', 'MYBL2', 'MYH11', 'MYO10', 'MYO5C', 'MYRIP', 'NASP', 'NAT1', 'NBEA', 'NBR1', 'NCAM2', 'NCAPD2', 'NCAPG2', 'NCAPG', 'NCAPH', 'NCK2', 'NCRNA00092', 'NCRNA00162', 'NDC80', 'NDUFAF4', 'NEIL3', 'NEK10', 'NEK11', 'NEK5', 'NEK9', 'NIP7', 'NME5', 'NOL10', 'NOP2', 'NOP58', 'NOSTRIN', 'NOTCH1', 'NOVA1', 'NPM2', 'NPNT', 'NR2E1', 'NRG2', 'NRIP2', 'NRTN', 'NT5DC2', 'NUBPL', 'NUDCD1', 'NUDT12', 'NUDT16', 'NUDT5', 'NUF2', 'NUP93', 'NXNL2', 'NXN', 'NXPH3', 'OCA2', 'ODC1', 'OIP5', 'OLAH', 'OPRK1', 'ORC1L', 'ORC6L', 'OSCP1', 'OSR1', 'P4HTM', 'PAK1IP1', 'PAMR1', 'PAPD7', 'PAPL', 'PAPSS1', 'PCBD2', 'PCDH8', 'PCNA', 'PCSK4', 'PDCD5', 'PDE7A', 'PDE9A', 'PDGFD', 'PDIA6', 'PDSS1', 'PEX11A', 'PFKP', 'PGBD5', 'PGGT1B', 'PGLYRP2', 'PGLYRP4', 'PGM5', 'PGPEP1', 'PGR', 'PHF15', 'PHGDH', 'PHOSPHO2', 'PHYHD1', 'PI3', 'PIF1', 'PLK1', 'PLK4', 'PLOD1', 'PM20D2', 'PNMA3', 'PNO1', 'PNPLA4', 'PNPLA7', 'POLQ', 'POLR1E', 'POLR2D', 'POLR3G', 'POP1', 'POU4F1', 'POU5F1', 'PPP1R14C', 'PPYR1', 'PRC1', 'PRDM13', 'PREX1', 'PRICKLE2', 'PRIM2', 'PRKAB1', 'PRKX', 'PRNP', 'PRR15', 'PRRT3', 'PRSS12', 'PRSS33', 'PRTFDC1', 'PSAPL1', 'PSAT1', 'PSMB2', 'PSMD14', 'PSME4', 'PSMG1', 'PTCHD1', 'PTDSS1', 'PTGR2', 'PTPN2', 'PTPRT', 'PTPRZ1', 'PTTG1', 'PTTG3P', 'PTX3', 'PVR', 'RAB5B', 'RABEP1', 'RACGAP1', 'RAD51AP1', 'RAD51', 'RAD54B', 'RAD54L', 'RAET1L', 'RAI2', 'RALGAPA1', 'RALGPS2', 'RANBP1', 'RAN', 'RAPGEF3', 'RARA', 'RARRES1', 'RASGEF1C', 'RBM17', 'RBM28', 'RBM38', 'RCOR2', 'RDH10', 'REEP1', 'REEP5', 'REEP6', 'RERG', 'RFC2', 'RFC4', 'RGMA', 'RGR', 'RGS20', 'RGS22', 'RHCG', 'RHEB', 'RHOB', 'RIOK1', 'RIPK2', 'RLBP1', 'RMND5B', 'RNASE4', 'RNASEH1', 'RND1', 'RNF103', 'RNF145', 'RNF8', 'ROPN1B', 'ROPN1', 'RPH3AL', 'RPIA', 'RPP40', 'RRP1B', 'RSU1', 'RTN4RL1', 'RUNDC1', 'S100B', 'SALL2', 'SBSN', 'SCCPDH', 'SCHIP1', 'SCN2B', 'SCN4B', 'SCN7A', 'SCNN1A', 'SCRG1', 'SCUBE2', 'SDPR', 'SEC14L4', 'SEC16A', 'SEH1L', 'SEMA3B', 'SEMA3C', 'SEMA3F', 'SEPHS1', 'SEPSECS', 'SERBP1', 'SERPINA11', 'SERPINA5', 'SERPINB5', 'SF3A3', 'SFRP1', 'SFRS13B', 'SFT2D2', 'SGOL1', 'SGOL2', 'SH3GL3', 'SHC4', 'SHCBP1', 'SIDT1', 'SKA1', 'SKA3', 'SKP1', 'SKP2', 'SLC15A1', 'SLC16A1', 'SLC16A6', 'SLC22A16', 'SLC22A5', 'SLC24A1', 'SLC25A13', 'SLC25A19', 'SLC26A9', 'SLC39A6', 'SLC39A9', 'SLC40A1', 'SLC43A3', 'SLC44A4', 'SLC46A1', 'SLC4A8', 'SLC6A11', 'SLC6A14', 'SLC6A15', 'SLC6A2', 'SLC7A13', 'SLC7A2', 'SLC7A5', 'SLC7A8', 'SMG5', 'SMOC1', 'SNED1', 'SNRPA1', 'SNRPG', 'SNX32', 'SOSTDC1', 'SOX10', 'SOX11', 'SOX8', 'SPAG5', 'SPARCL1', 'SPATA20', 'SPDEF', 'SPEF1', 'SPEF2', 'SPG11', 'SPRY2', 'SRD5A1', 'SRPK1', 'SSH3', 'ST3GAL6', 'ST8SIA1', 'STAC', 'STIL', 'STK32B', 'STK38', 'STMN1', 'SUGT1L1', 'SUOX', 'SUSD3', 'SUV39H2', 'SYBU', 'SYNJ2BP', 'SYNM', 'SYT17', 'SYT9', 'SYTL2', 'SYTL4', 'SYTL5', 'TADA2B', 'TAF11', 'TAF5', 'TAPT1', 'TBC1D7', 'TBC1D9', 'TBX19', 'TCAM1P', 'TCEAL1', 'TCEAL7', 'TCF19', 'TCF7L1', 'TCTN1', 'TENC1', 'TEX10', 'TFF1', 'TFF3', 'TGM1', 'THSD4', 'TIGD2', 'TIGD6', 'TIMM8A', 'TINAGL1', 'TLE3', 'TLX3', 'TMBIM4', 'TMBIM6', 'TMC5', 'TMCC2', 'TMEM144', 'TMEM171', 'TMEM206', 'TMEM25', 'TMEM39B', 'TMEM62', 'TMEM74', 'TMPRSS6', 'TMSB15A', 'TOX4', 'TP53INP1', 'TPCN1', 'TPRG1', 'TPSG1', 'TPX2', 'TRIM15', 'TRIM29', 'TRIM2', 'TRIM3', 'TRIM43', 'TRIML2', 'TRIP13', 'TROAP', 'TRPM8', 'TSC22D3', 'TSLP', 'TSPAN13', 'TSPAN15', 'TSPAN1', 'TTC18', 'TTC28', 'TTC36', 'TTC7A', 'TTC8', 'TTK', 'TTLL4', 'TTYH1', 'TUBA1C', 'TUBA3D', 'TUBA3E', 'TUBB', 'TYMS', 'UBASH3B', 'UBE2C', 'UBE2E3', 'UBE2T', 'UBE2V2', 'UBXN10', 'UBXN2A', 'UCK2', 'UGT8', 'ULBP1', 'ULBP2', 'ULBP3', 'UPF0639', 'UQCRHL', 'UQCRH', 'USP30', 'UTP11L', 'VGLL1', 'VIPR1', 'VPS39', 'WDR19', 'WDR65', 'WDR67', 'WDR77', 'WDR93', 'WFS1', 'WNK4', 'WNT6', 'WWP1', 'XBP1', 'XPC', 'XPO5', 'YARS', 'YBX1', 'YEATS2', 'ZBTB16', 'ZBTB42', 'ZBTB4', 'ZBTB7A', 'ZER1', 'ZIC1', 'ZIC4', 'ZMAT1', 'ZMYND10', 'ZNF280A', 'ZNF396', 'ZNF442', 'ZNF454', 'ZNF467', 'ZNF552', 'ZNF695', 'ZNF703', 'ZNF763']

In [10]:
"""
Fetch interactions for a specific gene or gene list
"""

import requests
import json
import io
import polars as pl

request_url = "https://webservice.thebiogrid.org/interactions/"
# List of genes to search for
# gene_list = ["STE11", "NMD4"]  # Yeast Genes STE11 and NMD4

# evidenceList = ["POSITIVE GENETIC", "PHENOTYPIC ENHANCEMENT"]

# These parameters can be modified to match any search criteria following
# the rules outlined in the Wiki: https://wiki.thebiogrid.org/doku.php/biogridrest
params = {
    "accesskey": "7bcc32a723cda4c96a00c69790c6c26e",
    "format": "tab3",  # Return results in TAB2 format
    "geneList": "|".join(gene_list),  # Must be | separated
    "searchNames": "true",  # Search against official names
    "includeInteractors": "false",  # Set to true to get any interaction involving EITHER gene, set to false to get interactions between genes
    # "taxId": 9606,  # Limit to Saccharomyces cerevisiae
    # "evidenceList": "|".join(evidenceList),  # Exclude these two evidence types
    # "includeEvidence": "false",  # If false "evidenceList" is evidence to exclude, if true "evidenceList" is evidence to show
    "includeHeader": "true",
}

# Additional options to try, you can uncomment them as necessary
# params["start"] = 5 # Specify where to start fetching results from if > 10,000 results being returned
# params["max"] = 10 # Specify the number of results to return, max is 10,000
# params["interSpeciesExcluded"] = "false" # true or false, If ‘true’, interactions with interactors from different species will be excluded (ex. no Human -> Mouse interactions)
# params["selfInteractionsExcluded"] = "false" # true or false, If ‘true’, interactions with one interactor will be excluded. (ex. no STE11 -> STE11 interactions)
# params["searchIds"] = "false" # true or false, If ‘true’, ENTREZ_GENE, ORDERED LOCUS and SYSTEMATIC_NAME (orf) will be examined for a match with the geneList
# params["searchSynonyms"] = "false" # true or false, If ‘true’, SYNONYMS will be examined for a match with the geneList
# params["searchBiogridIds"] = "false" # true or false, If ‘true’, BIOGRID INTERNAL IDS will be examined for a match with the geneList
# params["excludeGenes"] = "false" # true or false, If 'true' the geneList becomes a list of genes to EXCLUDE rather than to INCLUDE
# params["includeInteractorInteractions"] = "true" # true or false, If ‘true’ interactions between the geneList’s first order interactors will be included. Ignored if includeInteractors is ‘false’ or if excludeGenes is set to ‘true’.
# params["htpThreshold"] = 50 # Any publication with more than this many interactions will be excluded
# params["throughputTag"] = "any" # any, low, high. If set to low, only `low throughput` interactions will be returned, if set to high, only `high throughput` interactions will be returned
# params["additionalIdentifierTypes"] = "SGD|FLYBASE|REFSEQ" # You can specify a | separated list of additional identifier types to search against (see get_identifier_types.py)

r = requests.get(request_url, params=params)
interactions = r.text
i_df = pl.read_csv(
    io.StringIO(interactions),
    separator="\t"
)
i_df.head()

shape: (5, 24)
┌────────────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬──────┬───────────┐
│ #BioGRID   ┆ Entrez     ┆ Entrez     ┆ BioGRID ID ┆ … ┆ Phenotype ┆ Qualifica ┆ Tags ┆ Source    │
│ Interactio ┆ Gene       ┆ Gene       ┆ Interactor ┆   ┆ s         ┆ tions     ┆ ---  ┆ Database  │
│ n ID       ┆ Interactor ┆ Interactor ┆ A          ┆   ┆ ---       ┆ ---       ┆ str  ┆ ---       │
│ ---        ┆ A          ┆ B          ┆ ---        ┆   ┆ str       ┆ str       ┆      ┆ str       │
│ i64        ┆ ---        ┆ ---        ┆ i64        ┆   ┆           ┆           ┆      ┆           │
│            ┆ i64        ┆ i64        ┆            ┆   ┆           ┆           ┆      ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════╪═══════════╡
│ 143645     ┆ 851076     ┆ 851076     ┆ 31623      ┆ … ┆ -         ┆ -         ┆ -    ┆ BIOGRID   │
│ 146985     ┆ 851076     ┆ 851076     ┆ 31623      ┆ … ┆ -         ┆ -         ┆ -    ┆ BIOGRID   │
│ 147029     ┆ 851076     ┆ 851076     ┆ 31623      ┆ … ┆ -         ┆ -         ┆ -    ┆ BIOGRID   │
│ 147867     ┆ 851076     ┆ 851076     ┆ 31623      ┆ … ┆ -         ┆ -         ┆ -    ┆ BIOGRID   │
│ 147868     ┆ 851076     ┆ 851076     ┆ 31623      ┆ … ┆ -         ┆ -         ┆ -    ┆ BIOGRID   │
└────────────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴──────┴───────────┘

In [ ]:
# write interactions to file
with open('test_interactions.tsv', 'w') as f:
    f.write(interactions)

In [8]:
# print(interactions)
# int_df = pl.read_csv(interactions, separator='\t')

ComputeError: invalid glob pattern given

# Class counts

In [16]:
# get two columns, drop nan and reindex from 0
cM = clinicalMatrix[['sampleID', 'PAM50_mRNA_nature2012']].dropna().reset_index(drop=True)
# print(cM)

# filter rows with PAM50_mRNA_nature2012 == 'Normal'
cM = cM[cM['PAM50_mRNA_nature2012'] != 'Normal-like'].reset_index(drop=True)

names, counts = np.unique(cM['PAM50_mRNA_nature2012'].to_numpy(), return_counts=True)
for i, j in zip(names, counts):
    print(f"{i}: {j}")

Basal-like: 98
HER2-enriched: 58
Luminal A: 231
Luminal B: 127

In [29]:
# get two columns, drop nan and reindex from 0
cM = clinicalMatrix[['sampleID', 'PAM50Call_RNAseq']].dropna().reset_index(drop=True)
print(cM)
names, counts = np.unique(cM['PAM50Call_RNAseq'].to_numpy(), return_counts=True)
for i, j in zip(names, counts):
    print(f"{i}: {j}")

            sampleID PAM50Call_RNAseq
0    TCGA-A1-A0SB-01           Normal
1    TCGA-A1-A0SD-01             LumA
2    TCGA-A1-A0SE-01             LumA
3    TCGA-A1-A0SF-01             LumA
4    TCGA-A1-A0SG-01             LumA
..               ...              ...
951  TCGA-GM-A2DM-01             LumA
952  TCGA-GM-A2DN-01             LumA
953  TCGA-GM-A2DO-01             LumB
954  TCGA-GM-A3NY-01             LumA
955  TCGA-HN-A2NL-01            Basal

[956 rows x 2 columns]
Basal: 142
Her2: 67
LumA: 434
LumB: 194
Normal: 119

In [12]:
# read mrna brca data
mrna = pl.read_csv("BRCA/mrna.csv", has_header=False)
mrna.head()

shape: (5, 1_000)
┌──────────┬──────────┬──────────┬──────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ column_1 ┆ column_2 ┆ column_3 ┆ column_4 ┆ … ┆ column_997 ┆ column_998 ┆ column_999 ┆ column_10 │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ 00        │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64        ┆ f64        ┆ f64        ┆ ---       │
│          ┆          ┆          ┆          ┆   ┆            ┆            ┆            ┆ f64       │
╞══════════╪══════════╪══════════╪══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 0.200966 ┆ 0.179005 ┆ 0.532301 ┆ 0.211709 ┆ … ┆ 0.488912   ┆ 0.122566   ┆ 0.423955   ┆ 0.401625  │
│ 0.389212 ┆ 0.059248 ┆ 0.681862 ┆ 0.059248 ┆ … ┆ 0.621025   ┆ 0.277413   ┆ 0.552513   ┆ 0.384913  │
│ 0.36787  ┆ 0.054971 ┆ 0.600799 ┆ 0.0      ┆ … ┆ 0.629914   ┆ 0.162357   ┆ 0.515021   ┆ 0.366723  │
│ 0.306606 ┆ 0.05911  ┆ 0.560979 ┆ 0.077592 ┆ … ┆ 0.587933   ┆ 0.134054   ┆ 0.451911   ┆ 0.342593  │
│ 0.241916 ┆ 0.035355 ┆ 0.616187 ┆ 0.035355 ┆ … ┆ 0.52808    ┆ 0.194732   ┆ 0.604232   ┆ 0.405829  │
└──────────┴──────────┴──────────┴──────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [18]:
mrna_headers = pl.read_csv("BRCA/mrna_featname.csv", separator="|", has_header=False)
mrna_genes = mrna_headers["column_1"].to_numpy()

In [21]:
mrna_genes.shape

(1000,)

In [25]:
mrna.var()

shape: (1, 1_000)
┌──────────┬──────────┬──────────┬──────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ column_1 ┆ column_2 ┆ column_3 ┆ column_4 ┆ … ┆ column_997 ┆ column_998 ┆ column_999 ┆ column_10 │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---        ┆ ---        ┆ ---        ┆ 00        │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64        ┆ f64        ┆ f64        ┆ ---       │
│          ┆          ┆          ┆          ┆   ┆            ┆            ┆            ┆ f64       │
╞══════════╪══════════╪══════════╪══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 0.008022 ┆ 0.026082 ┆ 0.009043 ┆ 0.015763 ┆ … ┆ 0.006709   ┆ 0.009751   ┆ 0.008449   ┆ 0.002148  │
└──────────┴──────────┴──────────┴──────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [32]:
num_rows, num_cols = 10, 10

data = np.random.rand(num_rows, num_cols)

# Create column names (optional, you can customize these)
column_names = [f"col{i}" for i in range(num_cols)]

# Create the DataFrame from NumPy array and column names
df = pl.DataFrame(data, schema=column_names)

# Print the DataFrame
df

shape: (10, 10)
┌──────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ col0     ┆ col1     ┆ col2     ┆ col3     ┆ … ┆ col6     ┆ col7     ┆ col8     ┆ col9     │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 0.878595 ┆ 0.388049 ┆ 0.736731 ┆ 0.075935 ┆ … ┆ 0.271192 ┆ 0.437236 ┆ 0.83282  ┆ 0.926498 │
│ 0.124534 ┆ 0.799943 ┆ 0.870047 ┆ 0.552052 ┆ … ┆ 0.706904 ┆ 0.548569 ┆ 0.34363  ┆ 0.207802 │
│ 0.184589 ┆ 0.666814 ┆ 0.076169 ┆ 0.050483 ┆ … ┆ 0.982532 ┆ 0.354327 ┆ 0.335867 ┆ 0.930161 │
│ 0.122447 ┆ 0.684323 ┆ 0.379226 ┆ 0.92186  ┆ … ┆ 0.420772 ┆ 0.769737 ┆ 0.09762  ┆ 0.183642 │
│ 0.621008 ┆ 0.909692 ┆ 0.407601 ┆ 0.742202 ┆ … ┆ 0.403012 ┆ 0.951785 ┆ 0.668837 ┆ 0.503162 │
│ 0.970223 ┆ 0.320617 ┆ 0.29923  ┆ 0.333306 ┆ … ┆ 0.1756   ┆ 0.904397 ┆ 0.905118 ┆ 0.447846 │
│ 0.225181 ┆ 0.435141 ┆ 0.964514 ┆ 0.073433 ┆ … ┆ 0.641692 ┆ 0.566753 ┆ 0.040015 ┆ 0.814571 │
│ 0.046865 ┆ 0.981277 ┆ 0.327753 ┆ 0.309857 ┆ … ┆ 0.545018 ┆ 0.385473 ┆ 0.175469 ┆ 0.602734 │
│ 0.443936 ┆ 0.862401 ┆ 0.147666 ┆ 0.712932 ┆ … ┆ 0.353829 ┆ 0.968414 ┆ 0.303511 ┆ 0.434183 │
│ 0.684514 ┆ 0.250275 ┆ 0.770959 ┆ 0.463534 ┆ … ┆ 0.984099 ┆ 0.980647 ┆ 0.038822 ┆ 0.900223 │
└──────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [33]:
df.var()

shape: (1, 10)
┌────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ col0   ┆ col1     ┆ col2     ┆ col3     ┆ … ┆ col6     ┆ col7     ┆ col8     ┆ col9     │
│ ---    ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64    ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 0.1146 ┆ 0.069471 ┆ 0.097667 ┆ 0.095041 ┆ … ┆ 0.078139 ┆ 0.065248 ┆ 0.102952 ┆ 0.082083 │
└────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [46]:
df.var().to_numpy().argsort()

array([[7, 1, 6, 9, 3, 2, 4, 8, 0, 5]])

In [53]:
df.var()

shape: (1, 10)
┌────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ col0   ┆ col1     ┆ col2     ┆ col3     ┆ … ┆ col6     ┆ col7     ┆ col8     ┆ col9     │
│ ---    ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64    ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 0.1146 ┆ 0.069471 ┆ 0.097667 ┆ 0.095041 ┆ … ┆ 0.078139 ┆ 0.065248 ┆ 0.102952 ┆ 0.082083 │
└────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [61]:
df[df.var().melt().sort(pl.col("value"), descending=True)[:5]["variable"]]

shape: (10, 5)
┌──────────┬──────────┬──────────┬──────────┬──────────┐
│ col5     ┆ col0     ┆ col8     ┆ col4     ┆ col2     │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╪══════════╡
│ 0.314385 ┆ 0.878595 ┆ 0.83282  ┆ 0.963925 ┆ 0.736731 │
│ 0.588907 ┆ 0.124534 ┆ 0.34363  ┆ 0.148797 ┆ 0.870047 │
│ 0.900463 ┆ 0.184589 ┆ 0.335867 ┆ 0.767831 ┆ 0.076169 │
│ 0.068069 ┆ 0.122447 ┆ 0.09762  ┆ 0.096979 ┆ 0.379226 │
│ 0.218799 ┆ 0.621008 ┆ 0.668837 ┆ 0.400199 ┆ 0.407601 │
│ 0.729415 ┆ 0.970223 ┆ 0.905118 ┆ 0.0624   ┆ 0.29923  │
│ 0.992812 ┆ 0.225181 ┆ 0.040015 ┆ 0.126074 ┆ 0.964514 │
│ 0.103252 ┆ 0.046865 ┆ 0.175469 ┆ 0.14874  ┆ 0.327753 │
│ 0.796914 ┆ 0.443936 ┆ 0.303511 ┆ 0.574447 ┆ 0.147666 │
│ 0.823947 ┆ 0.684514 ┆ 0.038822 ┆ 0.355888 ┆ 0.770959 │
└──────────┴──────────┴──────────┴──────────┴──────────┘

In [63]:
from bipartite_gnn.preprocessing import FeatureSelection

fs = FeatureSelection(df, 5, 0)

In [64]:
fs.variatonal_selection()

shape: (10, 5)
┌──────────┬──────────┬──────────┬──────────┬──────────┐
│ col5     ┆ col0     ┆ col8     ┆ col4     ┆ col2     │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╪══════════╪══════════╡
│ 0.314385 ┆ 0.878595 ┆ 0.83282  ┆ 0.963925 ┆ 0.736731 │
│ 0.588907 ┆ 0.124534 ┆ 0.34363  ┆ 0.148797 ┆ 0.870047 │
│ 0.900463 ┆ 0.184589 ┆ 0.335867 ┆ 0.767831 ┆ 0.076169 │
│ 0.068069 ┆ 0.122447 ┆ 0.09762  ┆ 0.096979 ┆ 0.379226 │
│ 0.218799 ┆ 0.621008 ┆ 0.668837 ┆ 0.400199 ┆ 0.407601 │
│ 0.729415 ┆ 0.970223 ┆ 0.905118 ┆ 0.0624   ┆ 0.29923  │
│ 0.992812 ┆ 0.225181 ┆ 0.040015 ┆ 0.126074 ┆ 0.964514 │
│ 0.103252 ┆ 0.046865 ┆ 0.175469 ┆ 0.14874  ┆ 0.327753 │
│ 0.796914 ┆ 0.443936 ┆ 0.303511 ┆ 0.574447 ┆ 0.147666 │
│ 0.823947 ┆ 0.684514 ┆ 0.038822 ┆ 0.355888 ┆ 0.770959 │
└──────────┴──────────┴──────────┴──────────┴──────────┘

In [66]:
# Assuming self.data is your DataFrame and self.n_features is the number of features you want to select
top_features = df.var().top_k(5, by="value")["variable"]

# Select the top features from the original DataFrame
selected_data = df.select(top_features)

selected_data

ColumnNotFoundError: value