In [9]:
%load_ext autoreload
%autoreload 2

import numpy as np
import polars as pl
import torch
import torch_geometric as pyg
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split, StratifiedKFold
import matplotlib.pyplot as plt

from bipartite_gnn.graph_visualizatons import visualize_graph, visualize_embeddings
from baseline_evals.feature_selection import variance_filtering, class_variational_selection
from bipartite_gnn.preprocessing import mrmr_selection
from baseline_evals.knn_eval import knn_eval
from baseline_evals.svm_eval import svm_eval
from baseline_evals.xgboost_eval import xgboost_eval
from baseline_evals.mlp_eval import mlp_eval
from gnn_experiments.mogonet_eval import mogonet_eval

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [10]:
mrna = pl.read_csv('MDS_data_preprocessed/mrna.csv')
mirna = pl.read_csv('MDS_data_preprocessed/mirna.csv')
circrna = pl.read_csv('MDS_data_preprocessed/circrna.csv')
te_counts = pl.read_csv('MDS_data_preprocessed/te_counts.csv')
pirna = pl.read_csv('MDS_data_preprocessed/pirna.csv')

annot = pl.read_csv('MDS_data_preprocessed/annotations.csv')

In [4]:
mrna

shape: (19_873, 75)
┌──────────────┬───────┬───────┬───────┬───┬───────┬───────┬───────┬───────┐
│ GENE_NAME    ┆ V1884 ┆ N58   ┆ V630  ┆ … ┆ V806  ┆ V513  ┆ V1565 ┆ V1920 │
│ ---          ┆ ---   ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str          ┆ i64   ┆ i64   ┆ i64   ┆   ┆ i64   ┆ i64   ┆ i64   ┆ i64   │
╞══════════════╪═══════╪═══════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ RILPL1       ┆ 187   ┆ 235   ┆ 538   ┆ … ┆ 458   ┆ 263   ┆ 384   ┆ 649   │
│ RAB4B        ┆ 1296  ┆ 951   ┆ 1261  ┆ … ┆ 801   ┆ 989   ┆ 1682  ┆ 943   │
│ TIGAR        ┆ 1229  ┆ 184   ┆ 609   ┆ … ┆ 499   ┆ 400   ┆ 508   ┆ 204   │
│ DNAH3        ┆ 5     ┆ 0     ┆ 12    ┆ … ┆ 3     ┆ 0     ┆ 11    ┆ 22    │
│ RP11-432M8.3 ┆ 2     ┆ 1     ┆ 1     ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 3     │
│ …            ┆ …     ┆ …     ┆ …     ┆ … ┆ …     ┆ …     ┆ …     ┆ …     │
│ CYP4F2       ┆ 291   ┆ 182   ┆ 157   ┆ … ┆ 11    ┆ 127   ┆ 281   ┆ 225   │
│ TENM1        ┆ 131   ┆ 32    ┆ 16    ┆ … ┆ 19    ┆ 7     ┆ 49    ┆ 34    │
│ BATF3        ┆ 117   ┆ 67    ┆ 351   ┆ … ┆ 472   ┆ 74    ┆ 227   ┆ 39    │
│ PPP6R1       ┆ 24306 ┆ 28193 ┆ 23945 ┆ … ┆ 27759 ┆ 18774 ┆ 43097 ┆ 16402 │
│ OR8D4        ┆ 0     ┆ 0     ┆ 0     ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 34    │
└──────────────┴───────┴───────┴───────┴───┴───────┴───────┴───────┴───────┘

In [11]:
sample_names = annot['SAMPLE_NAME'].to_list()
sample_names = [name.split('_')[0] for name in sample_names]

assert sample_names == mrna.columns[1:]  == mirna.columns[1:] == circrna.columns[1:] == te_counts.columns[1:]

In [25]:
# prepare pirnas too
# pirna = pl.read_excel("MDS_data/piRNA_counts.xlsx")

# pirna_samples = pirna.columns[1:]

# pirna_samples = [s.split("_")[0] for s in pirna_samples]

# common_samples_w_pirna = list(set(pirna_samples).intersection(set(sample_names)))

# annot_pi = annot.filter(pl.col("sample_ids").is_in(common_samples_w_pirna))

# pirna.columns = ['piRNA'] + pirna_samples
# pirna = pirna.select(['piRNA'] + common_samples_w_pirna)
# pirna_X = pirna.to_numpy()[:, 1:]
# pirna_zeros_mask = pirna_X.sum(axis=1) < 300
# pirna_zeros_idx = np.where(pirna_zeros_mask == False)[0]
# pirna_names = pirna['piRNA'].to_list()
# pirna_names = [name.split('/')[0] for name in pirna_names]
# pirna = pirna.with_columns(piRNA=pl.Series(pirna_names))
# pirna[pirna_zeros_idx].write_csv("MDS_data_preprocessed/pirna.csv")

shape: (556, 105)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ piRNA     ┆ V1565_S17 ┆ N58_S10-U ┆ V1874_S15 ┆ … ┆ V2147_S8- ┆ V2224_S19 ┆ V2089_S1- ┆ V788_S2- │
│ ---       ┆ -UMIs     ┆ MIs       ┆ -UMIs     ┆   ┆ UMIs      ┆ -UMIs     ┆ UMIs      ┆ UMIs     │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ i64       ┆ i64       ┆ i64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ hsa_piR_0 ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 06779/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ579258/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 07653/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ580430/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 09540/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ582872/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 00302/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ570363/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 00390/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ570472/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ hsa_piR_0 ┆ 315       ┆ 274       ┆ 230       ┆ … ┆ 273       ┆ 161       ┆ 175       ┆ 43       │
│ 20814/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ598650/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 316       ┆ 458       ┆ 493       ┆ … ┆ 281       ┆ 574       ┆ 183       ┆ 120      │
│ 20815/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ598651/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 2732      ┆ 1064      ┆ 1346      ┆ … ┆ 749       ┆ 1192      ┆ 921       ┆ 391      │
│ 20829/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ598677/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 131       ┆ 177       ┆ 441       ┆ … ┆ 171       ┆ 398       ┆ 271       ┆ 217      │
│ 21032/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ598918/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 265       ┆ 188       ┆ 264       ┆ … ┆ 151       ┆ 311       ┆ 337       ┆ 161      │
│ 21462/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ599459/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
y_d = annot['1 disease'].to_numpy()
y_r = annot['2 risk'].to_numpy()
y_m = annot['3 mutations (SF3B1only_wt)'].to_numpy()

np.unique(y_d, return_counts=True), np.unique(y_r, return_counts=True), np.unique(y_m, return_counts=True)

((array([1, 2]), array([13, 61])),
 (array([0, 1, 2]), array([21, 29, 24])),
 (array([0, 1, 2]), array([48, 14, 12])))

In [5]:
mrna_names = mrna.columns[1:]
mirna_names = mirna.columns[1:]
circrna_names = circrna.columns[1:]
te_names = te_counts.columns[1:]

y_d = annot['1 disease'].to_numpy()
y_r = annot['2 risk'].to_numpy()
y_m = annot['3 mutations (SF3B1only_wt)'].to_numpy()

y = y_d

annotated_samples_mask = y != 0

y = y - 1  # move to 0-indexing

In [58]:
y

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
mrna_X = mrna.to_numpy()[:, 1:].T
mirna_X = mirna.to_numpy()[:, 1:].T
circrna_X = circrna.to_numpy()[:, 1:].T
te_X = te_counts.to_numpy()[:, 1:].T

mrna_X = mrna_X[annotated_samples_mask]
mirna_X = mirna_X[annotated_samples_mask]
circrna_X = circrna_X[annotated_samples_mask]
te_X = te_X[annotated_samples_mask]

y = y[annotated_samples_mask]

print(np.unique(y, return_counts=True))

X = np.hstack([mrna_X])

(array([0, 1]), array([13, 61]))

In [9]:
knn_eval(X, y, select_n_features=True)

500
| KNN | 0.91 +/- 0.08 | 0.76 +/- 0.21 | 0.89 +/- 0.10 |
study.best_value=0.8854446886446887, study.best_params={'n_neighbors': 6, 'n_features': 2166}

In [10]:
svm_eval(X, y, select_n_features=True)

Trial 1 / 40
| SVM | 0.81 +/- 0.13 | 0.75 +/- 0.11 | 0.82 +/- 0.11 |
Trial 2 / 40
Trial 3 / 40
| SVM | 0.84 +/- 0.14 | 0.79 +/- 0.15 | 0.85 +/- 0.13 |
Trial 4 / 40
Trial 5 / 40
Trial 6 / 40
Trial 7 / 40
Trial 8 / 40
Trial 9 / 40
Trial 10 / 40
Trial 11 / 40
| SVM | 0.85 +/- 0.11 | 0.79 +/- 0.11 | 0.86 +/- 0.09 |
Trial 12 / 40
Trial 13 / 40
Trial 14 / 40
Trial 15 / 40
Trial 16 / 40
Trial 17 / 40
Trial 18 / 40
Trial 19 / 40
Trial 20 / 40
Trial 21 / 40
Trial 22 / 40
Trial 23 / 40
Trial 24 / 40
Trial 25 / 40
Trial 26 / 40
Trial 27 / 40
Trial 28 / 40
Trial 29 / 40
Trial 30 / 40
Trial 31 / 40
Trial 32 / 40
Trial 33 / 40
Trial 34 / 40
Trial 35 / 40
Trial 36 / 40
Trial 37 / 40
Trial 38 / 40
Trial 39 / 40
Trial 40 / 40
| LIN SVM | 0.85 +/- 0.11 | 0.79 +/- 0.11 | 0.86 +/- 0.09 |
study.best_value=0.8623449121999845, study.best_params={'C': 0.14646961644890166, 'class_weight': 'balanced', 'n_features': 529}

{'acc': 0.8523809523809524,
 'f1_macro': 0.7929974695192087,
 'f1_weighted': 0.8623449121999845,
 'acc_std': 0.10596709368153238,
 'f1_macro_std': 0.1074278261937699,
 'f1_weighted_std': 0.09291001559594489}

In [11]:
xgboost_eval(X, y)

0 / 50
ACC: [0.86666667 0.66666667 0.66666667 0.8        0.85714286]
F1M: [0.71153846 0.4        0.4        0.72049689 0.70833333]
F1W: [0.86666667 0.64       0.64       0.80993789 0.85714286]
| XGBoost | 0.77 +/- 0.09 | 0.59 +/- 0.15 | 0.76 +/- 0.10 |
1 / 50
ACC: [0.73333333 0.66666667 0.66666667 0.8        0.85714286]
F1M: [0.42307692 0.4        0.4        0.72049689 0.70833333]
F1W: [0.73333333 0.64       0.64       0.80993789 0.85714286]
2 / 50
ACC: [0.8        0.8        0.8        0.93333333 0.92857143]
F1M: [0.44444444 0.44444444 0.44444444 0.88       0.81333333]
F1W: [0.77037037 0.71111111 0.71111111 0.928      0.91809524]
| XGBoost | 0.85 +/- 0.06 | 0.61 +/- 0.20 | 0.81 +/- 0.10 |
3 / 50
ACC: [0.93333333 0.93333333 0.93333333 0.73333333 1.        ]
F1M: [0.81481481 0.9068323  0.88       0.7        1.        ]
F1W: [0.92345679 0.93664596 0.928      0.76       1.        ]
| XGBoost | 0.91 +/- 0.09 | 0.86 +/- 0.10 | 0.91 +/- 0.08 |
4 / 50
ACC: [0.86666667 0.8        0.93333333 0.93333333 1.        ]
F1M: [0.46428571 0.64       0.88       0.88       1.        ]
F1W: [0.8047619 0.784     0.928     0.928     1.       ]
5 / 50
Pruning trial
ACC: [0.73333333 0.66666667 0.66666667 0.8        0.        ]
F1M: [0.42307692 0.4        0.4        0.72049689 0.        ]
F1W: [0.73333333 0.64       0.64       0.80993789 0.        ]
6 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.8        1.        ]
F1M: [0.81481481 0.9068323  0.82954545 0.76190476 1.        ]
F1W: [0.92345679 0.93664596 0.87727273 0.81904762 1.        ]
| XGBoost | 0.91 +/- 0.07 | 0.86 +/- 0.08 | 0.91 +/- 0.06 |
7 / 50
Pruning trial
ACC: [0.73333333 0.66666667 0.66666667 0.8        0.        ]
F1M: [0.42307692 0.4        0.4        0.72049689 0.        ]
F1W: [0.73333333 0.64       0.64       0.80993789 0.        ]
8 / 50
Pruning trial
ACC: [0.86666667 0.66666667 0.66666667 0.8        0.        ]
F1M: [0.71153846 0.4        0.4        0.72049689 0.        ]
F1W: [0.86666667 0.64       0.64       0.80993789 0.        ]
9 / 50
Pruning trial
ACC: [0.86666667 0.73333333 0.66666667 0.8        0.        ]
F1M: [0.46428571 0.42307692 0.4        0.72049689 0.        ]
F1W: [0.8047619  0.67692308 0.64       0.80993789 0.        ]
10 / 50
ACC: [0.93333333 0.93333333 0.93333333 0.8        1.        ]
F1M: [0.81481481 0.9068323  0.9068323  0.76190476 1.        ]
F1W: [0.92345679 0.93664596 0.93664596 0.81904762 1.        ]
| XGBoost | 0.92 +/- 0.07 | 0.88 +/- 0.08 | 0.92 +/- 0.06 |
11 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.8        1.        ]
F1M: [0.81481481 0.9068323  0.82954545 0.76190476 1.        ]
F1W: [0.92345679 0.93664596 0.87727273 0.81904762 1.        ]
12 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.8        1.        ]
F1M: [0.81481481 0.9068323  0.82954545 0.76190476 1.        ]
F1W: [0.92345679 0.93664596 0.87727273 0.81904762 1.        ]
13 / 50
ACC: [0.93333333 0.93333333 0.8        0.8        1.        ]
F1M: [0.81481481 0.9068323  0.72049689 0.76190476 1.        ]
F1W: [0.92345679 0.93664596 0.80993789 0.81904762 1.        ]
14 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.8        1.        ]
F1M: [0.81481481 0.9068323  0.79166667 0.76190476 1.        ]
F1W: [0.92345679 0.93664596 0.86666667 0.81904762 1.        ]
15 / 50
ACC: [0.93333333 0.86666667 0.93333333 0.8        1.        ]
F1M: [0.81481481 0.79166667 0.9068323  0.72049689 1.        ]
F1W: [0.92345679 0.86666667 0.93664596 0.80993789 1.        ]
16 / 50
Pruning trial
ACC: [0.8        0.8        0.66666667 0.66666667 0.        ]
F1M: [0.44444444 0.44444444 0.6031746  0.6031746  0.        ]
F1W: [0.77037037 0.71111111 0.6984127  0.6984127  0.        ]
17 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.8        1.        ]
F1M: [0.81481481 0.9068323  0.79166667 0.76190476 1.        ]
F1W: [0.92345679 0.93664596 0.86666667 0.81904762 1.        ]
18 / 50
ACC: [0.93333333 1.         0.8        0.8        1.        ]
F1M: [0.81481481 1.         0.72049689 0.76190476 1.        ]
F1W: [0.92345679 1.         0.80993789 0.81904762 1.        ]
19 / 50
Pruning trial
ACC: [0.73333333 0.8        0.66666667 0.66666667 0.        ]
F1M: [0.58333333 0.44444444 0.6031746  0.6031746  0.        ]
F1W: [0.76666667 0.71111111 0.6984127  0.6984127  0.        ]
20 / 50
ACC: [0.93333333 1.         0.86666667 0.86666667 1.        ]
F1M: [0.81481481 1.         0.82954545 0.82954545 1.        ]
F1W: [0.92345679 1.         0.87727273 0.87727273 1.        ]
| XGBoost | 0.93 +/- 0.06 | 0.89 +/- 0.09 | 0.94 +/- 0.06 |
21 / 50
ACC: [0.93333333 0.86666667 0.86666667 0.86666667 1.        ]
F1M: [0.81481481 0.79166667 0.82954545 0.82954545 1.        ]
F1W: [0.92345679 0.86666667 0.87727273 0.87727273 1.        ]
22 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.86666667 1.        ]
F1M: [0.81481481 0.9068323  0.82954545 0.82954545 1.        ]
F1W: [0.92345679 0.93664596 0.87727273 0.87727273 1.        ]
23 / 50
Pruning trial
ACC: [0.86666667 0.93333333 0.86666667 0.8        0.        ]
F1M: [0.46428571 0.88       0.79166667 0.72049689 0.        ]
F1W: [0.8047619  0.928      0.86666667 0.80993789 0.        ]
24 / 50
Pruning trial
ACC: [0.86666667 0.93333333 0.86666667 0.8        0.        ]
F1M: [0.46428571 0.88       0.79166667 0.72049689 0.        ]
F1W: [0.8047619  0.928      0.86666667 0.80993789 0.        ]
25 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.8        1.        ]
F1M: [0.81481481 0.88       0.79166667 0.72049689 1.        ]
F1W: [0.92345679 0.928      0.86666667 0.80993789 1.        ]
26 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.86666667 1.        ]
F1M: [0.81481481 0.9068323  0.82954545 0.82954545 1.        ]
F1W: [0.92345679 0.93664596 0.87727273 0.87727273 1.        ]
27 / 50
Pruning trial
ACC: [0.93333333 0.93333333 0.86666667 0.73333333 1.        ]
F1M: [0.81481481 0.9068323  0.82954545 0.7        1.        ]
F1W: [0.92345679 0.93664596 0.87727273 0.76       1.        ]
28 / 50
Pruning trial
ACC: [0.86666667 0.66666667 0.66666667 0.8        0.        ]
F1M: [0.46428571 0.4        0.4        0.72049689 0.        ]
F1W: [0.8047619  0.64       0.64       0.80993789 0.        ]
29 / 50
Pruning trial
ACC: [0.73333333 0.66666667 0.66666667 0.8        0.        ]
F1M: [0.42307692 0.4        0.4        0.72049689 0.        ]
F1W: [0.73333333 0.64       0.64       0.80993789 0.        ]
30 / 50
Pruning trial
ACC: [0.73333333 0.66666667 0.66666667 0.8        0.        ]
F1M: [0.42307692 0.4        0.4        0.72049689 0.        ]
F1W: [0.73333333 0.64       0.64       0.80993789 0.        ]
31 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.86666667 1.        ]
F1M: [0.81481481 0.9068323  0.82954545 0.82954545 1.        ]
F1W: [0.92345679 0.93664596 0.87727273 0.87727273 1.        ]
32 / 50
Pruning trial
ACC: [0.86666667 0.93333333 0.86666667 0.8        0.        ]
F1M: [0.46428571 0.88       0.79166667 0.72049689 0.        ]
F1W: [0.8047619  0.928      0.86666667 0.80993789 0.        ]
33 / 50
ACC: [0.93333333 0.86666667 0.93333333 0.86666667 1.        ]
F1M: [0.81481481 0.79166667 0.9068323  0.82954545 1.        ]
F1W: [0.92345679 0.86666667 0.93664596 0.87727273 1.        ]
34 / 50
Pruning trial
ACC: [0.86666667 0.93333333 0.86666667 0.8        0.        ]
F1M: [0.46428571 0.88       0.79166667 0.72049689 0.        ]
F1W: [0.8047619  0.928      0.86666667 0.80993789 0.        ]
35 / 50
Pruning trial
ACC: [0.86666667 0.86666667 0.86666667 0.86666667 0.        ]
F1M: [0.46428571 0.71153846 0.79166667 0.79166667 0.        ]
F1W: [0.8047619  0.83846154 0.86666667 0.86666667 0.        ]
36 / 50
ACC: [0.93333333 1.         0.86666667 0.8        1.        ]
F1M: [0.81481481 1.         0.82954545 0.76190476 1.        ]
F1W: [0.92345679 1.         0.87727273 0.81904762 1.        ]
37 / 50
Pruning trial
ACC: [0.73333333 0.66666667 0.66666667 0.8        0.        ]
F1M: [0.42307692 0.4        0.4        0.72049689 0.        ]
F1W: [0.73333333 0.64       0.64       0.80993789 0.        ]
38 / 50
Pruning trial
ACC: [0.93333333 0.93333333 0.8        0.8        1.        ]
F1M: [0.81481481 0.9068323  0.72049689 0.76190476 1.        ]
F1W: [0.92345679 0.93664596 0.80993789 0.81904762 1.        ]
39 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.8        1.        ]
F1M: [0.81481481 0.9068323  0.82954545 0.76190476 1.        ]
F1W: [0.92345679 0.93664596 0.87727273 0.81904762 1.        ]
40 / 50
Pruning trial
ACC: [0.73333333 0.66666667 0.66666667 0.8        0.        ]
F1M: [0.42307692 0.4        0.4        0.72049689 0.        ]
F1W: [0.73333333 0.64       0.64       0.80993789 0.        ]
41 / 50
ACC: [0.93333333 1.         0.86666667 0.86666667 1.        ]
F1M: [0.81481481 1.         0.82954545 0.82954545 1.        ]
F1W: [0.92345679 1.         0.87727273 0.87727273 1.        ]
42 / 50
ACC: [0.93333333 1.         0.86666667 0.86666667 1.        ]
F1M: [0.81481481 1.         0.82954545 0.82954545 1.        ]
F1W: [0.92345679 1.         0.87727273 0.87727273 1.        ]
43 / 50
ACC: [0.93333333 1.         0.86666667 0.8        1.        ]
F1M: [0.81481481 1.         0.82954545 0.76190476 1.        ]
F1W: [0.92345679 1.         0.87727273 0.81904762 1.        ]
44 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.8        1.        ]
F1M: [0.81481481 0.9068323  0.82954545 0.76190476 1.        ]
F1W: [0.92345679 0.93664596 0.87727273 0.81904762 1.        ]
45 / 50
ACC: [0.93333333 1.         0.86666667 0.8        1.        ]
F1M: [0.81481481 1.         0.82954545 0.76190476 1.        ]
F1W: [0.92345679 1.         0.87727273 0.81904762 1.        ]
46 / 50
ACC: [0.93333333 1.         0.86666667 0.8        1.        ]
F1M: [0.81481481 1.         0.82954545 0.76190476 1.        ]
F1W: [0.92345679 1.         0.87727273 0.81904762 1.        ]
47 / 50
ACC: [0.93333333 0.86666667 0.93333333 0.8        1.        ]
F1M: [0.81481481 0.79166667 0.9068323  0.72049689 1.        ]
F1W: [0.92345679 0.86666667 0.93664596 0.80993789 1.        ]
48 / 50
Pruning trial
ACC: [0.86666667 0.66666667 0.66666667 0.8        0.        ]
F1M: [0.71153846 0.4        0.4        0.72049689 0.        ]
F1W: [0.86666667 0.64       0.64       0.80993789 0.        ]
49 / 50
ACC: [0.93333333 0.93333333 0.86666667 0.8        1.        ]
F1M: [0.81481481 0.9068323  0.79166667 0.76190476 1.        ]
F1W: [0.92345679 0.93664596 0.86666667 0.81904762 1.        ]
| XGBoost | 0.93 +/- 0.06 | 0.89 +/- 0.09 | 0.94 +/- 0.06 |
study.best_value=0.9356004489337822, study.best_params={'booster': 'gblinear', 'lambda': 1.9007943402435523e-06, 'alpha': 7.235842957592092e-06}

In [8]:
mlp_eval(X, y, reg_type=None, n_trials=15)

Trial 0 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 0.75  1.   ]
[0.46666667 0.66666667 0.79487179 0.73333333 1.        ]
[0.81666667 0.75       0.85897436 0.76666667 1.        ]
{'acc': 0.85, 'f1_macro': 0.7323076923076923, 'f1_weighted': 0.8384615384615384, 'acc_std': 0.09354143466934853, 'f1_macro_std': 0.1734637652177653, 'f1_weighted_std': 0.08940963505258638}
Trial 1 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.75  0.75  0.75  0.875 1.   ]
[0.42857143 0.66666667 0.66666667 0.85454545 1.        ]
[0.75       0.75       0.75       0.88181818 1.        ]
Trial 2 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.75  0.875 1.   ]
[0.46666667 0.66666667 0.66666667 0.85454545 1.        ]
[0.81666667 0.75       0.75       0.88181818 1.        ]
Trial 3 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.875 0.75  1.    1.   ]
[0.46666667 0.79487179 0.66666667 1.         1.        ]
[0.81666667 0.85897436 0.75       1.         1.        ]
{'acc': 0.9, 'f1_macro': 0.7856410256410257, 'f1_weighted': 0.8851282051282052, 'acc_std': 0.09354143466934853, 'f1_macro_std': 0.20390403951541392, 'f1_weighted_std': 0.10002169389933914}
Trial 4 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 0.75  1.   ]
[0.46666667 0.66666667 0.79487179 0.73333333 1.        ]
[0.81666667 0.75       0.85897436 0.76666667 1.        ]
Trial 5 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 0.875 1.   ]
[0.46666667 0.66666667 0.79487179 0.85454545 1.        ]
[0.81666667 0.75       0.85897436 0.88181818 1.        ]
Trial 6 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Pruning trial after 4 evals, cause 0.6788156288156287 < 0.8851282051282052
[0.875 0.75  0.625 0.75  0.   ]
[0.46666667 0.42857143 0.38461538 0.73333333 0.        ]
[0.81666667 0.64285714 0.57692308 0.76666667 0.        ]
Trial 7 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 1.    1.   ]
[0.46666667 0.66666667 0.79487179 1.         1.        ]
[0.81666667 0.75       0.85897436 1.         1.        ]
Trial 8 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.75  0.75  0.625 1.    1.   ]
[0.42857143 0.66666667 0.56363636 1.         1.        ]
[0.75       0.75       0.64545455 1.         1.        ]
Trial 9 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5

Exception ignored in: <function _releaseLock at 0x732c003b8ea0>
Traceback (most recent call last):
  File "/home/lubojjan/micromamba/envs/diploma/lib/python3.12/logging/__init__.py", line 243, in _releaseLock
    def _releaseLock():

KeyboardInterrupt:

{'acc': 0.9, 'f1_macro': 0.7856410256410257, 'f1_weighted': 0.8851282051282052, 'acc_std': 0.09354143466934853, 'f1_macro_std': 0.20390403951541392, 'f1_weighted_std': 0.10002169389933914}

In [7]:
mlp_eval(X, y, reg_type='l1', n_trials=15)

Trial 0 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875      0.625      0.5        0.75       0.85714287]
[0.46666667 0.56363636 0.33333333 0.66666667 0.78787879]
[0.81666667 0.64545455 0.5        0.75       0.87445887]
{'acc': 0.7214285731315613, 'f1_macro': 0.5636363636363637, 'f1_weighted': 0.7173160173160172, 'acc_std': 0.14223077128025008, 'f1_macro_std': 0.15706209986485523, 'f1_weighted_std': 0.13268232310424447}
Trial 1 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.625      0.5        0.5        0.5        0.85714287]
[0.38461538 0.33333333 0.46666667 0.33333333 0.78787879]
[0.67307692 0.5        0.53333333 0.5        0.87445887]
Trial 2 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.75  0.75  1.   ]
[0.46666667 0.66666667 0.42857143 0.73333333 1.        ]
[0.81666667 0.75       0.64285714 0.76666667 1.        ]
{'acc': 0.825, 'f1_macro': 0.659047619047619, 'f1_weighted': 0.7952380952380953, 'acc_std': 0.1, 'f1_macro_std': 0.2058905770189967, 'f1_weighted_std': 0.1170208423786994}
Trial 3 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.75  0.75  0.875 0.875 1.   ]
[0.42857143 0.66666667 0.79487179 0.85454545 1.        ]
[0.75       0.75       0.85897436 0.88181818 1.        ]
{'acc': 0.85, 'f1_macro': 0.748931068931069, 'f1_weighted': 0.8481585081585081, 'acc_std': 0.09354143466934853, 'f1_macro_std': 0.19271652131980704, 'f1_weighted_std': 0.09335521447911105}
Trial 4 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 1.    1.   ]
[0.46666667 0.66666667 0.79487179 1.         1.        ]
[0.81666667 0.75       0.85897436 1.         1.        ]
{'acc': 0.9, 'f1_macro': 0.7856410256410257, 'f1_weighted': 0.8851282051282052, 'acc_std': 0.09354143466934853, 'f1_macro_std': 0.20390403951541392, 'f1_weighted_std': 0.10002169389933914}
Trial 5 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Pruning trial after 3 evals, cause 0.675 < 0.8851282051282052
[0.5  0.75 0.25 0.   0.  ]
[0.33333333 0.73333333 0.2        0.         0.        ]
[0.58333333 0.76666667 0.1        0.         0.        ]
Trial 6 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Pruning trial after 4 evals, cause 0.6788156288156287 < 0.8851282051282052
[0.875 0.625 0.75  0.875 0.   ]
[0.46666667 0.38461538 0.42857143 0.79487179 0.        ]
[0.81666667 0.57692308 0.64285714 0.85897436 0.        ]
Trial 7 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Pruning trial after 3 evals, cause 0.6634615384615385 < 0.8851282051282052
[0.75  0.625 0.75  0.    0.   ]
[0.42857143 0.38461538 0.66666667 0.         0.        ]
[0.75       0.57692308 0.75       0.         0.        ]
Trial 8 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.75  0.75  0.875 1.    1.   ]
[0.42857143 0.66666667 0.79487179 1.         1.        ]
[0.75       0.75       0.85897436 1.         1.        ]
Trial 9 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
Pruning trial after 5 evals, cause 0.6414835164835164 < 0.8851282051282052
[0.625     0.75      0.625     0.5       0.2857143]
[0.38461538 0.66666667 0.61904762 0.5        0.28571429]
[0.67307692 0.75       0.64285714 0.5        0.28571429]
Trial 10 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 1.    1.   ]
[0.46666667 0.66666667 0.79487179 1.         1.        ]
[0.81666667 0.75       0.85897436 1.         1.        ]
Trial 11 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.75  1.    1.   ]
[0.46666667 0.66666667 0.66666667 1.         1.        ]
[0.81666667 0.75       0.75       1.         1.        ]
Trial 12 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 1.    1.   ]
[0.46666667 0.66666667 0.79487179 1.         1.        ]
[0.81666667 0.75       0.85897436 1.         1.        ]
Trial 13 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.75  1.    1.   ]
[0.46666667 0.66666667 0.66666667 1.         1.        ]
[0.81666667 0.75       0.75       1.         1.        ]
Trial 14 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.75 0.75 0.75 1.   1.  ]
[0.42857143 0.66666667 0.66666667 1.         1.        ]
[0.75 0.75 0.75 1.   1.  ]
study.best_value=2.5707692307692307, study.best_params={'lr': 0.0006020110974547146, 'l1_lambda': 0.0018878348900282507, 'l2_lambda': 0.00025807608309932727, 'proj_dim': 62, 'hidden_channels': 100, 'n_features': 1046}
| MLP | 0.90 +/- 0.09 | 0.79 +/- 0.20 | 0.89 +/- 0.10 |

In [8]:
mlp_eval(X, y, reg_type='inner_mat', n_trials=15)

Trial 0 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 1.    1.   ]
[0.46666667 0.66666667 0.79487179 1.         1.        ]
[0.81666667 0.75       0.85897436 1.         1.        ]
{'acc': 0.9, 'f1_macro': 0.7856410256410257, 'f1_weighted': 0.8851282051282052, 'acc_std': 0.09354143466934853, 'f1_macro_std': 0.20390403951541392, 'f1_weighted_std': 0.10002169389933914}
Trial 1 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
Pruning trial after 5 evals, cause 0.6784965034965035 < 0.8851282051282052
[0.625      0.75       0.625      0.625      0.71428573]
[0.38461538 0.66666667 0.56363636 0.56363636 0.65      ]
[0.67307692 0.75       0.64545455 0.64545455 0.75714286]
Trial 2 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Pruning trial after 3 evals, cause 0.6666666666666666 < 0.8851282051282052
[0.5  0.75 0.5  0.   0.  ]
[0.33333333 0.66666667 0.5        0.         0.        ]
[0.58333333 0.75       0.5        0.         0.        ]
Trial 3 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.625      0.75       0.75       0.75       0.85714287]
[0.38461538 0.66666667 0.73333333 0.66666667 0.78787879]
[0.67307692 0.75       0.76666667 0.75       0.87445887]
Trial 4 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.75  0.875 0.875 0.875 1.   ]
[0.42857143 0.79487179 0.79487179 0.85454545 1.        ]
[0.75       0.85897436 0.85897436 0.88181818 1.        ]
Trial 5 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.75  0.875 0.875 0.875 1.   ]
[0.42857143 0.85454545 0.79487179 0.85454545 1.        ]
[0.75       0.88181818 0.85897436 0.88181818 1.        ]
Trial 6 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
Pruning trial after 5 evals, cause 0.6768037518037517 < 0.8851282051282052
[0.75  0.875 0.75  0.375 1.   ]
[0.42857143 0.85454545 0.66666667 0.36507937 1.        ]
[0.75       0.88181818 0.75       0.32539683 1.        ]
Trial 7 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.75  0.875 0.625 0.75  1.   ]
[0.42857143 0.85454545 0.56363636 0.73333333 1.        ]
[0.75       0.88181818 0.64545455 0.76666667 1.        ]
Trial 8 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Pruning trial after 3 evals, cause 0.6666666666666666 < 0.8851282051282052
[0.5  0.75 0.5  0.   0.  ]
[0.33333333 0.66666667 0.5        0.         0.        ]
[0.58333333 0.75       0.5        0.         0.        ]
Trial 9 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.75  0.875 0.75  0.875 1.   ]
[0.42857143 0.85454545 0.66666667 0.85454545 1.        ]
[0.75       0.88181818 0.75       0.88181818 1.        ]
Trial 10 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 1.    1.   ]
[0.46666667 0.66666667 0.79487179 1.         1.        ]
[0.81666667 0.75       0.85897436 1.         1.        ]
Trial 11 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 1.    1.   ]
[0.46666667 0.66666667 0.79487179 1.         1.        ]
[0.81666667 0.75       0.85897436 1.         1.        ]
Trial 12 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
Pruning trial after 5 evals, cause 0.6778471528471528 < 0.8851282051282052
[0.625      0.75       0.625      0.625      0.71428573]
[0.38461538 0.66666667 0.56363636 0.61904762 0.65      ]
[0.67307692 0.75       0.64545455 0.64285714 0.75714286]
Trial 13 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 1.    1.   ]
[0.46666667 0.66666667 0.79487179 1.         1.        ]
[0.81666667 0.75       0.85897436 1.         1.        ]
Trial 14 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.875 0.75  0.875 0.875 1.   ]
[0.46666667 0.66666667 0.79487179 0.85454545 1.        ]
[0.81666667 0.75       0.85897436 0.88181818 1.        ]
study.best_value=2.5707692307692307, study.best_params={'lr': 0.00015649700754149815, 'l1_lambda': 0.00011696386902486234, 'l2_lambda': 0.00017852820207215917, 'proj_dim': 236, 'hidden_channels': 51, 'n_features': 1596}
| MLP | 0.90 +/- 0.09 | 0.79 +/- 0.20 | 0.89 +/- 0.10 |

In [14]:
val, test = mogonet_eval(
    input_omics={
        "mrna": mrna,
        # "meth": meth,
        # "mirna": mirna,
    },
    n_input_features={
        "mrna": 3000,
        "meth": 1000,
        "mirna": 200,
    },
    y=y,
    params={
        "encoder_hidden_channels": {
            "mrna": 300,
            # "meth": 100,
            # "mirna": 50,
        },
        "encoder_type": "gat",
        "num_classes": 2,
        "graph_style": "threshold",
        "avg_degree": 15,
        # "knn": 15,
        "dropout": 0.0,
        "epochs": 400,
        "log_interval": 50,
        "save_best_model": False,
    }
)

dict_keys(['mrna'])
Fold 1 / 5
Building graph for mrna
0.75 tensor(65.9730)
0.875 tensor(33.5946)
0.9375 tensor(3.8919)
0.90625 tensor(18.)
0.921875 tensor(10.5946)
0.9140625 tensor(13.9189)
0.91015625 tensor(16.1622)
0.912109375 tensor(15.1351)
Isolated samples = 11, avg degree = 15.13513469696045
Epoch: 050:
Train Loss: 0.2412, Train Acc: 0.8983, Train F1 Macro: 0.8520, Train F1 Weighted: 0.9039
Val Loss: 0.5861, Val Acc: 0.5714, Val F1 Macro: 0.3636, Val F1 Weighted: 0.6234
Test Loss: 0.4981, Test Acc: 0.8750, Test F1 Macro: 0.4667, Test F1 Weighted: 0.8167
##################################################
Epoch: 100:
Train Loss: 0.2126, Train Acc: 0.9153, Train F1 Macro: 0.8731, Train F1 Weighted: 0.9190
Val Loss: 0.5303, Val Acc: 0.7143, Val F1 Macro: 0.4167, Val F1 Weighted: 0.7143
Test Loss: 0.4472, Test Acc: 0.8750, Test F1 Macro: 0.4667, Test F1 Weighted: 0.8167
##################################################
Epoch: 150:
Train Loss: 0.2092, Train Acc: 0.9153, Train F1 Macro: 0.8731, Train F1 Weighted: 0.9190
Val Loss: 0.5217, Val Acc: 0.7143, Val F1 Macro: 0.4167, Val F1 Weighted: 0.7143
Test Loss: 0.4335, Test Acc: 0.8750, Test F1 Macro: 0.4667, Test F1 Weighted: 0.8167
##################################################
Epoch: 200:
Train Loss: 0.2081, Train Acc: 0.9153, Train F1 Macro: 0.8731, Train F1 Weighted: 0.9190
Val Loss: 0.5209, Val Acc: 0.7143, Val F1 Macro: 0.4167, Val F1 Weighted: 0.7143
Test Loss: 0.4319, Test Acc: 0.8750, Test F1 Macro: 0.4667, Test F1 Weighted: 0.8167
##################################################
Epoch: 250:
Train Loss: 0.2064, Train Acc: 0.9153, Train F1 Macro: 0.8731, Train F1 Weighted: 0.9190
Val Loss: 0.5217, Val Acc: 0.7143, Val F1 Macro: 0.4167, Val F1 Weighted: 0.7143
Test Loss: 0.4324, Test Acc: 0.8750, Test F1 Macro: 0.4667, Test F1 Weighted: 0.8167
##################################################
Epoch: 300:
Train Loss: 0.2031, Train Acc: 0.9153, Train F1 Macro: 0.8731, Train F1 Weighted: 0.9190
Val Loss: 0.5214, Val Acc: 0.7143, Val F1 Macro: 0.4167, Val F1 Weighted: 0.7143
Test Loss: 0.4288, Test Acc: 0.8750, Test F1 Macro: 0.4667, Test F1 Weighted: 0.8167
##################################################
Epoch: 350:
Train Loss: 0.1973, Train Acc: 0.9153, Train F1 Macro: 0.8731, Train F1 Weighted: 0.9190
Val Loss: 0.5267, Val Acc: 0.7143, Val F1 Macro: 0.4167, Val F1 Weighted: 0.7143
Test Loss: 0.4294, Test Acc: 0.8750, Test F1 Macro: 0.4667, Test F1 Weighted: 0.8167
##################################################
Epoch: 400:
Train Loss: 0.1925, Train Acc: 0.9322, Train F1 Macro: 0.8954, Train F1 Weighted: 0.9343
Val Loss: 0.5276, Val Acc: 0.7143, Val F1 Macro: 0.4167, Val F1 Weighted: 0.7143
Test Loss: 0.4262, Test Acc: 0.8750, Test F1 Macro: 0.4667, Test F1 Weighted: 0.8167
##################################################
Fold 2 / 5
Building graph for mrna
0.75 tensor(59.7838)
0.875 tensor(21.8649)
0.9375 tensor(1.3514)
0.90625 tensor(9.2432)
0.890625 tensor(15.5946)
0.8984375 tensor(12.4324)
0.89453125 tensor(13.9189)
0.892578125 tensor(14.7297)
Isolated samples = 11, avg degree = 14.729729652404785
Epoch: 050:
Train Loss: 0.2520, Train Acc: 0.8475, Train F1 Macro: 0.7716, Train F1 Weighted: 0.8586
Val Loss: 0.2009, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.2361, Test Acc: 0.6250, Test F1 Macro: 0.6190, Test F1 Weighted: 0.6429
##################################################
Epoch: 100:
Train Loss: 0.2052, Train Acc: 0.8983, Train F1 Macro: 0.8431, Train F1 Weighted: 0.9046
Val Loss: 0.1724, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.2306, Test Acc: 0.6250, Test F1 Macro: 0.6190, Test F1 Weighted: 0.6429
##################################################
Epoch: 150:
Train Loss: 0.2059, Train Acc: 0.8814, Train F1 Macro: 0.8319, Train F1 Weighted: 0.8922
Val Loss: 0.1834, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.3170, Test Acc: 0.6250, Test F1 Macro: 0.6190, Test F1 Weighted: 0.6429
##################################################
Epoch: 200:
Train Loss: 0.2033, Train Acc: 0.8475, Train F1 Macro: 0.7943, Train F1 Weighted: 0.8634
Val Loss: 0.1805, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.3152, Test Acc: 0.6250, Test F1 Macro: 0.6190, Test F1 Weighted: 0.6429
##################################################
Epoch: 250:
Train Loss: 0.2030, Train Acc: 0.8475, Train F1 Macro: 0.7943, Train F1 Weighted: 0.8634
Val Loss: 0.1799, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.3139, Test Acc: 0.6250, Test F1 Macro: 0.6190, Test F1 Weighted: 0.6429
##################################################
Epoch: 300:
Train Loss: 0.2028, Train Acc: 0.8475, Train F1 Macro: 0.7943, Train F1 Weighted: 0.8634
Val Loss: 0.1795, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.3138, Test Acc: 0.6250, Test F1 Macro: 0.6190, Test F1 Weighted: 0.6429
##################################################
Epoch: 350:
Train Loss: 0.2025, Train Acc: 0.8475, Train F1 Macro: 0.7943, Train F1 Weighted: 0.8634
Val Loss: 0.1790, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.3135, Test Acc: 0.6250, Test F1 Macro: 0.6190, Test F1 Weighted: 0.6429
##################################################
Epoch: 400:
Train Loss: 0.2022, Train Acc: 0.8644, Train F1 Macro: 0.8127, Train F1 Weighted: 0.8778
Val Loss: 0.1785, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.3133, Test Acc: 0.6250, Test F1 Macro: 0.6190, Test F1 Weighted: 0.6429
##################################################
Fold 3 / 5
Building graph for mrna
0.75 tensor(65.0811)
0.875 tensor(35.1351)
0.9375 tensor(4.2703)
0.90625 tensor(19.1351)
0.921875 tensor(11.3243)
0.9140625 tensor(15.0541)
Isolated samples = 10, avg degree = 15.054054260253906
Epoch: 050:
Train Loss: 0.2580, Train Acc: 0.8305, Train F1 Macro: 0.7765, Train F1 Weighted: 0.8491
Val Loss: 0.1307, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 0.3293, Test Acc: 0.8750, Test F1 Macro: 0.7949, Test F1 Weighted: 0.8590
##################################################
Epoch: 100:
Train Loss: 0.2263, Train Acc: 0.8305, Train F1 Macro: 0.7765, Train F1 Weighted: 0.8491
Val Loss: 0.1234, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.2345, Test Acc: 0.8750, Test F1 Macro: 0.8545, Test F1 Weighted: 0.8818
##################################################
Epoch: 150:
Train Loss: 0.2230, Train Acc: 0.8305, Train F1 Macro: 0.7765, Train F1 Weighted: 0.8491
Val Loss: 0.1214, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.2314, Test Acc: 0.8750, Test F1 Macro: 0.8545, Test F1 Weighted: 0.8818
##################################################
Epoch: 200:
Train Loss: 0.2217, Train Acc: 0.8305, Train F1 Macro: 0.7765, Train F1 Weighted: 0.8491
Val Loss: 0.1200, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.2307, Test Acc: 0.8750, Test F1 Macro: 0.8545, Test F1 Weighted: 0.8818
##################################################
Epoch: 250:
Train Loss: 0.2205, Train Acc: 0.8305, Train F1 Macro: 0.7765, Train F1 Weighted: 0.8491
Val Loss: 0.1185, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.2297, Test Acc: 0.8750, Test F1 Macro: 0.8545, Test F1 Weighted: 0.8818
##################################################
Epoch: 300:
Train Loss: 0.2193, Train Acc: 0.8305, Train F1 Macro: 0.7765, Train F1 Weighted: 0.8491
Val Loss: 0.1169, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.2288, Test Acc: 0.8750, Test F1 Macro: 0.8545, Test F1 Weighted: 0.8818
##################################################
Epoch: 350:
Train Loss: 0.2182, Train Acc: 0.8305, Train F1 Macro: 0.7765, Train F1 Weighted: 0.8491
Val Loss: 0.1155, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.2278, Test Acc: 0.8750, Test F1 Macro: 0.8545, Test F1 Weighted: 0.8818
##################################################
Epoch: 400:
Train Loss: 0.2171, Train Acc: 0.8305, Train F1 Macro: 0.7765, Train F1 Weighted: 0.8491
Val Loss: 0.1141, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.2270, Test Acc: 0.8750, Test F1 Macro: 0.8545, Test F1 Weighted: 0.8818
##################################################
Fold 4 / 5
Building graph for mrna
0.75 tensor(66.3784)
0.875 tensor(32.6757)
0.9375 tensor(4.0811)
0.90625 tensor(17.4324)
0.921875 tensor(10.2703)
0.9140625 tensor(13.3784)
0.91015625 tensor(15.5676)
0.912109375 tensor(14.4054)
0.9111328125 tensor(15.)
Isolated samples = 12, avg degree = 15.0
Epoch: 050:
Train Loss: 0.0515, Train Acc: 0.9831, Train F1 Macro: 0.9710, Train F1 Weighted: 0.9834
Val Loss: 0.0915, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 1.7158, Test Acc: 0.8750, Test F1 Macro: 0.7949, Test F1 Weighted: 0.8590
##################################################
Epoch: 100:
Train Loss: 0.0046, Train Acc: 1.0000, Train F1 Macro: 1.0000, Train F1 Weighted: 1.0000
Val Loss: 0.0017, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 2.6844, Test Acc: 0.8750, Test F1 Macro: 0.7949, Test F1 Weighted: 0.8590
##################################################
Epoch: 150:
Train Loss: 0.0025, Train Acc: 1.0000, Train F1 Macro: 1.0000, Train F1 Weighted: 1.0000
Val Loss: 0.0031, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 2.9072, Test Acc: 0.8750, Test F1 Macro: 0.7949, Test F1 Weighted: 0.8590
##################################################
Epoch: 200:
Train Loss: 0.0022, Train Acc: 1.0000, Train F1 Macro: 1.0000, Train F1 Weighted: 1.0000
Val Loss: 0.0074, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 2.9445, Test Acc: 0.8750, Test F1 Macro: 0.7949, Test F1 Weighted: 0.8590
##################################################
Epoch: 250:
Train Loss: 0.0022, Train Acc: 1.0000, Train F1 Macro: 1.0000, Train F1 Weighted: 1.0000
Val Loss: 0.0088, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 2.9484, Test Acc: 0.8750, Test F1 Macro: 0.7949, Test F1 Weighted: 0.8590
##################################################
Epoch: 300:
Train Loss: 0.0022, Train Acc: 1.0000, Train F1 Macro: 1.0000, Train F1 Weighted: 1.0000
Val Loss: 0.0093, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 2.9501, Test Acc: 0.8750, Test F1 Macro: 0.7949, Test F1 Weighted: 0.8590
##################################################
Epoch: 350:
Train Loss: 0.0022, Train Acc: 1.0000, Train F1 Macro: 1.0000, Train F1 Weighted: 1.0000
Val Loss: 0.0096, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 2.9519, Test Acc: 0.8750, Test F1 Macro: 0.7949, Test F1 Weighted: 0.8590
##################################################
Epoch: 400:
Train Loss: 0.0022, Train Acc: 1.0000, Train F1 Macro: 1.0000, Train F1 Weighted: 1.0000
Val Loss: 0.0105, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 2.9538, Test Acc: 0.8750, Test F1 Macro: 0.7949, Test F1 Weighted: 0.8590
##################################################
Fold 5 / 5
Building graph for mrna
0.75 tensor(66.1351)
0.875 tensor(34.9459)
0.9375 tensor(3.8108)
0.90625 tensor(17.9730)
0.921875 tensor(10.2703)
0.9140625 tensor(14.2432)
0.91015625 tensor(15.6757)
0.912109375 tensor(14.9730)
Isolated samples = 11, avg degree = 14.972972869873047
Epoch: 050:
Train Loss: 0.5042, Train Acc: 0.6333, Train F1 Macro: 0.6053, Train F1 Weighted: 0.6719
Val Loss: 0.4430, Val Acc: 0.7143, Val F1 Macro: 0.6500, Val F1 Weighted: 0.7571
Test Loss: 0.4994, Test Acc: 0.5714, Test F1 Macro: 0.5333, Test F1 Weighted: 0.6286
##################################################
Epoch: 100:
Train Loss: 0.3431, Train Acc: 0.7833, Train F1 Macro: 0.7378, Train F1 Weighted: 0.8070
Val Loss: 0.2725, Val Acc: 0.7143, Val F1 Macro: 0.6500, Val F1 Weighted: 0.7571
Test Loss: 0.1582, Test Acc: 1.0000, Test F1 Macro: 1.0000, Test F1 Weighted: 1.0000
##################################################
Epoch: 150:
Train Loss: 0.2706, Train Acc: 0.8167, Train F1 Macro: 0.7701, Train F1 Weighted: 0.8356
Val Loss: 0.1307, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.0334, Test Acc: 1.0000, Test F1 Macro: 1.0000, Test F1 Weighted: 1.0000
##################################################
Epoch: 200:
Train Loss: 0.2613, Train Acc: 0.8333, Train F1 Macro: 0.7869, Train F1 Weighted: 0.8499
Val Loss: 0.1216, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.0319, Test Acc: 1.0000, Test F1 Macro: 1.0000, Test F1 Weighted: 1.0000
##################################################
Epoch: 250:
Train Loss: 0.2435, Train Acc: 0.8500, Train F1 Macro: 0.8043, Train F1 Weighted: 0.8642
Val Loss: 0.1008, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.0272, Test Acc: 1.0000, Test F1 Macro: 1.0000, Test F1 Weighted: 1.0000
##################################################
Epoch: 300:
Train Loss: 0.2293, Train Acc: 0.8667, Train F1 Macro: 0.8222, Train F1 Weighted: 0.8785
Val Loss: 0.0947, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.0206, Test Acc: 1.0000, Test F1 Macro: 1.0000, Test F1 Weighted: 1.0000
##################################################
Epoch: 350:
Train Loss: 0.2216, Train Acc: 0.9000, Train F1 Macro: 0.8602, Train F1 Weighted: 0.9075
Val Loss: 0.0969, Val Acc: 0.8571, Val F1 Macro: 0.7879, Val F1 Weighted: 0.8745
Test Loss: 0.0226, Test Acc: 1.0000, Test F1 Macro: 1.0000, Test F1 Weighted: 1.0000
##################################################
Epoch: 400:
Train Loss: 0.2195, Train Acc: 0.9000, Train F1 Macro: 0.8602, Train F1 Weighted: 0.9075
Val Loss: 0.0865, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 0.0201, Test Acc: 1.0000, Test F1 Macro: 1.0000, Test F1 Weighted: 1.0000
##################################################

In [15]:
print("MOGONET GAT (mrna only) results:")
print(f"| MOGONET GAT (mrna only) val | {val[:, 0].mean():.2f} +/- {val[:, 0].std():.2f} | {val[:, 1].mean():.2f} +/- {val[:, 1].std():.2f} | {val[:, 2].mean():.2f} +/- {val[:, 2].std():.2f} |")
print(f"| MOGONET GAT (mrna only) test | {test[:, 0].mean():.2f} +/- {test[:, 0].std():.2f} | {test[:, 1].mean():.2f} +/- {test[:, 1].std():.2f} | {test[:, 2].mean():.2f} +/- {test[:, 2].std():.2f} |")

MOGONET GAT (mrna only) results:
| MOGONET GAT (mrna only) val | 0.94 +/- 0.13 | 0.93 +/- 0.16 | 0.95 +/- 0.11 |
| MOGONET GAT (mrna only) test | 0.93 +/- 0.07 | 0.89 +/- 0.10 | 0.93 +/- 0.07 |