In [60]:
%load_ext autoreload
%autoreload 2

import numpy as np
import polars as pl
import torch
import torch_geometric as pyg
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split, StratifiedKFold
import matplotlib.pyplot as plt

from bipartite_gnn.graph_visualizatons import visualize_graph, visualize_embeddings
from baseline_evals.feature_selection import variance_filtering, class_variational_selection
from bipartite_gnn.preprocessing import mrmr_selection
from baseline_evals.knn_eval import knn_eval
from baseline_evals.svm_eval import svm_eval
from baseline_evals.xgboost_eval import xgboost_eval
from baseline_evals.mlp_eval import mlp_eval
from gnn_experiments.mogonet_eval import mogonet_eval

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [61]:
mrna = pl.read_csv('MDS_data_preprocessed/mrna.csv')
mirna = pl.read_csv('MDS_data_preprocessed/mirna.csv')
circrna = pl.read_csv('MDS_data_preprocessed/circrna.csv')
te_counts = pl.read_csv('MDS_data_preprocessed/te_counts.csv')
pirna = pl.read_csv('MDS_data_preprocessed/pirna.csv')

annot = pl.read_csv('MDS_data_preprocessed/annotations.csv')

In [20]:
mrna.shape, mirna.shape, circrna.shape, te_counts.shape, pirna.shape, annot.shape

((19873, 75), (1879, 75), (69, 75), (687, 75), (219, 67), (74, 5))

In [21]:
sample_names = annot['SAMPLE_NAME'].to_list()
sample_names = [name.split('_')[0] for name in sample_names]

assert sample_names == mrna.columns[1:]  == mirna.columns[1:] == circrna.columns[1:] == te_counts.columns[1:]

In [22]:
pirna_sample_names = pirna.columns[1:]

all_common_sample_names = list(set(pirna_sample_names).intersection(set(sample_names)))

In [25]:
mrna

shape: (19_873, 75)
┌──────────────┬───────┬───────┬───────┬───┬───────┬───────┬───────┬───────┐
│ GENE_NAME    ┆ V1884 ┆ N58   ┆ V630  ┆ … ┆ V806  ┆ V513  ┆ V1565 ┆ V1920 │
│ ---          ┆ ---   ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str          ┆ i64   ┆ i64   ┆ i64   ┆   ┆ i64   ┆ i64   ┆ i64   ┆ i64   │
╞══════════════╪═══════╪═══════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ RILPL1       ┆ 187   ┆ 235   ┆ 538   ┆ … ┆ 458   ┆ 263   ┆ 384   ┆ 649   │
│ RAB4B        ┆ 1296  ┆ 951   ┆ 1261  ┆ … ┆ 801   ┆ 989   ┆ 1682  ┆ 943   │
│ TIGAR        ┆ 1229  ┆ 184   ┆ 609   ┆ … ┆ 499   ┆ 400   ┆ 508   ┆ 204   │
│ DNAH3        ┆ 5     ┆ 0     ┆ 12    ┆ … ┆ 3     ┆ 0     ┆ 11    ┆ 22    │
│ RP11-432M8.3 ┆ 2     ┆ 1     ┆ 1     ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 3     │
│ …            ┆ …     ┆ …     ┆ …     ┆ … ┆ …     ┆ …     ┆ …     ┆ …     │
│ CYP4F2       ┆ 291   ┆ 182   ┆ 157   ┆ … ┆ 11    ┆ 127   ┆ 281   ┆ 225   │
│ TENM1        ┆ 131   ┆ 32    ┆ 16    ┆ … ┆ 19    ┆ 7     ┆ 49    ┆ 34    │
│ BATF3        ┆ 117   ┆ 67    ┆ 351   ┆ … ┆ 472   ┆ 74    ┆ 227   ┆ 39    │
│ PPP6R1       ┆ 24306 ┆ 28193 ┆ 23945 ┆ … ┆ 27759 ┆ 18774 ┆ 43097 ┆ 16402 │
│ OR8D4        ┆ 0     ┆ 0     ┆ 0     ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 34    │
└──────────────┴───────┴───────┴───────┴───┴───────┴───────┴───────┴───────┘

In [29]:
te_counts

shape: (687, 75)
┌──────────┬─────────┬─────────┬─────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ TE       ┆ V1884   ┆ N58     ┆ V630    ┆ … ┆ V806    ┆ V513    ┆ V1565   ┆ V1920   │
│ ---      ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ str      ┆ f64     ┆ f64     ┆ f64     ┆   ┆ f64     ┆ f64     ┆ f64     ┆ f64     │
╞══════════╪═════════╪═════════╪═════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ ALU      ┆ 13599.0 ┆ 7019.28 ┆ 6877.89 ┆ … ┆ 7599.44 ┆ 7370.1  ┆ 7059.21 ┆ 9787.8  │
│ AluJb    ┆ 44735.8 ┆ 26406.7 ┆ 24896.5 ┆ … ┆ 28709.9 ┆ 25891.1 ┆ 27218.6 ┆ 38261.4 │
│ AluJo    ┆ 4257.09 ┆ 4019.45 ┆ 2666.19 ┆ … ┆ 4184.29 ┆ 3155.55 ┆ 3744.24 ┆ 5137.53 │
│ AluJr    ┆ 1806.28 ┆ 1220.17 ┆ 1063.58 ┆ … ┆ 1238.01 ┆ 1206.32 ┆ 1180.33 ┆ 1694.92 │
│ AluJr4   ┆ 10841.0 ┆ 6707.35 ┆ 6414.47 ┆ … ┆ 7286.93 ┆ 6622.88 ┆ 7417.67 ┆ 9023.09 │
│ …        ┆ …       ┆ …       ┆ …       ┆ … ┆ …       ┆ …       ┆ …       ┆ …       │
│ X5A_LINE ┆ 3.0     ┆ 4.0     ┆ 4.0     ┆ … ┆ 8.0     ┆ 14.0    ┆ 2.0     ┆ 11.0    │
│ X5B_LINE ┆ 5.0     ┆ 8.0     ┆ 8.0     ┆ … ┆ 14.0    ┆ 7.0     ┆ 8.0     ┆ 1.0     │
│ X6A_LINE ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ 2.0     │
│ X6B_LINE ┆ 0.0     ┆ 0.0     ┆ 1.0     ┆ … ┆ 5.0     ┆ 14.0    ┆ 2.0     ┆ 0.0     │
│ X8_LINE  ┆ 0.0     ┆ 1.0     ┆ 0.0     ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ 1.0     │
└──────────┴─────────┴─────────┴─────────┴───┴─────────┴─────────┴─────────┴─────────┘

In [30]:
mrna_s = mrna.select(['GENE_NAME'] + all_common_sample_names)
mirna_s = mirna.select(['GENE_NAME'] + all_common_sample_names)
circrna_s = circrna.select(['circRNA_ID'] + all_common_sample_names)
te_counts_s = te_counts.select(['TE'] + all_common_sample_names)

In [35]:
annot_s = annot.filter(pl.col('sample_ids').is_in(all_common_sample_names))

In [34]:
annot

shape: (74, 5)
┌─────────────┬───────────┬────────┬────────────────────────────┬────────────┐
│ SAMPLE_NAME ┆ 1 disease ┆ 2 risk ┆ 3 mutations (SF3B1only_wt) ┆ sample_ids │
│ ---         ┆ ---       ┆ ---    ┆ ---                        ┆ ---        │
│ str         ┆ i64       ┆ i64    ┆ i64                        ┆ str        │
╞═════════════╪═══════════╪════════╪════════════════════════════╪════════════╡
│ V1884_S17   ┆ 2         ┆ 2      ┆ 0                          ┆ V1884      │
│ N58_S18     ┆ 1         ┆ 0      ┆ 0                          ┆ N58        │
│ V630_S11    ┆ 2         ┆ 1      ┆ 1                          ┆ V630       │
│ N60_S15     ┆ 1         ┆ 0      ┆ 0                          ┆ N60        │
│ V1297_S10   ┆ 2         ┆ 2      ┆ 0                          ┆ V1297      │
│ …           ┆ …         ┆ …      ┆ …                          ┆ …          │
│ V1048_S12   ┆ 2         ┆ 1      ┆ 0                          ┆ V1048      │
│ V806_S1     ┆ 2         ┆ 2      ┆ 2                          ┆ V806       │
│ V513_S16    ┆ 2         ┆ 2      ┆ 1                          ┆ V513       │
│ V1565_S13   ┆ 2         ┆ 2      ┆ 0                          ┆ V1565      │
│ V1920_S14   ┆ 2         ┆ 1      ┆ 0                          ┆ V1920      │
└─────────────┴───────────┴────────┴────────────────────────────┴────────────┘

In [56]:
import os

In [59]:
for mirna_file in os.listdir('BRCA_PROCESSED_DATA/mrmr_selected/mirna'):
    print(mirna_file)
    # mirna = pl.read_csv(f'MDS_data_preprocessed/mirna/{mirna_file}')
    # mirna_s = mirna.select(['GENE_NAME'] + all_common_sample_names)
    # mirna_s.write_csv(f'MDS_data_preprocessed/mirna/{mirna_file}')

mirna_fold_0.csv
mirna_fold_1.csv
mirna_fold_4.csv
mirna_fold_3.csv
mirna_fold_2.csv

In [38]:
mrna

shape: (19_873, 75)
┌──────────────┬───────┬───────┬───────┬───┬───────┬───────┬───────┬───────┐
│ GENE_NAME    ┆ V1884 ┆ N58   ┆ V630  ┆ … ┆ V806  ┆ V513  ┆ V1565 ┆ V1920 │
│ ---          ┆ ---   ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str          ┆ i64   ┆ i64   ┆ i64   ┆   ┆ i64   ┆ i64   ┆ i64   ┆ i64   │
╞══════════════╪═══════╪═══════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ RILPL1       ┆ 187   ┆ 235   ┆ 538   ┆ … ┆ 458   ┆ 263   ┆ 384   ┆ 649   │
│ RAB4B        ┆ 1296  ┆ 951   ┆ 1261  ┆ … ┆ 801   ┆ 989   ┆ 1682  ┆ 943   │
│ TIGAR        ┆ 1229  ┆ 184   ┆ 609   ┆ … ┆ 499   ┆ 400   ┆ 508   ┆ 204   │
│ DNAH3        ┆ 5     ┆ 0     ┆ 12    ┆ … ┆ 3     ┆ 0     ┆ 11    ┆ 22    │
│ RP11-432M8.3 ┆ 2     ┆ 1     ┆ 1     ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 3     │
│ …            ┆ …     ┆ …     ┆ …     ┆ … ┆ …     ┆ …     ┆ …     ┆ …     │
│ CYP4F2       ┆ 291   ┆ 182   ┆ 157   ┆ … ┆ 11    ┆ 127   ┆ 281   ┆ 225   │
│ TENM1        ┆ 131   ┆ 32    ┆ 16    ┆ … ┆ 19    ┆ 7     ┆ 49    ┆ 34    │
│ BATF3        ┆ 117   ┆ 67    ┆ 351   ┆ … ┆ 472   ┆ 74    ┆ 227   ┆ 39    │
│ PPP6R1       ┆ 24306 ┆ 28193 ┆ 23945 ┆ … ┆ 27759 ┆ 18774 ┆ 43097 ┆ 16402 │
│ OR8D4        ┆ 0     ┆ 0     ┆ 0     ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 34    │
└──────────────┴───────┴───────┴───────┴───┴───────┴───────┴───────┴───────┘

In [37]:
y_d = annot_s['1 disease'].to_numpy()
y_r = annot_s['2 risk'].to_numpy()
y_m = annot_s['3 mutations (SF3B1only_wt)'].to_numpy()

np.unique(y_d, return_counts=True), np.unique(y_r, return_counts=True), np.unique(y_m, return_counts=True)

((array([1, 2]), array([ 7, 59])),
 (array([0, 1, 2]), array([15, 27, 24])),
 (array([0, 1, 2]), array([41, 13, 12])))

In [ ]:
y_d = annot['1 disease'].to_numpy()
y_r = annot['2 risk'].to_numpy()
y_m = annot['3 mutations (SF3B1only_wt)'].to_numpy()

np.unique(y_d, return_counts=True), np.unique(y_r, return_counts=True), np.unique(y_m, return_counts=True)

In [45]:
labels = [(y_d, 'disease'), (y_r, 'risk'), (y_m, 'mutation')]

In [47]:
mirna_s

shape: (1_879, 67)
┌───────────┬──────┬──────┬───────┬───┬──────┬──────┬───────┬──────┐
│ GENE_NAME ┆ V888 ┆ V108 ┆ V2089 ┆ … ┆ V883 ┆ V655 ┆ V1699 ┆ V624 │
│ ---       ┆ ---  ┆ ---  ┆ ---   ┆   ┆ ---  ┆ ---  ┆ ---   ┆ ---  │
│ str       ┆ i64  ┆ i64  ┆ i64   ┆   ┆ i64  ┆ i64  ┆ i64   ┆ i64  │
╞═══════════╪══════╪══════╪═══════╪═══╪══════╪══════╪═══════╪══════╡
│ MIR4802   ┆ 3    ┆ 5    ┆ 0     ┆ … ┆ 2    ┆ 2    ┆ 2     ┆ 13   │
│ MIR4751   ┆ 1    ┆ 1    ┆ 1     ┆ … ┆ 1    ┆ 1    ┆ 1     ┆ 1    │
│ MIR378A   ┆ 4    ┆ 7    ┆ 4     ┆ … ┆ 2    ┆ 4    ┆ 5     ┆ 10   │
│ MIR578    ┆ 0    ┆ 0    ┆ 0     ┆ … ┆ 0    ┆ 2    ┆ 0     ┆ 0    │
│ MIR32     ┆ 13   ┆ 15   ┆ 2     ┆ … ┆ 8    ┆ 5    ┆ 17    ┆ 4    │
│ …         ┆ …    ┆ …    ┆ …     ┆ … ┆ …    ┆ …    ┆ …     ┆ …    │
│ MIR3187   ┆ 45   ┆ 9    ┆ 46    ┆ … ┆ 7    ┆ 32   ┆ 41    ┆ 7    │
│ MIR4692   ┆ 3    ┆ 0    ┆ 0     ┆ … ┆ 0    ┆ 0    ┆ 0     ┆ 0    │
│ MIR4270   ┆ 0    ┆ 0    ┆ 0     ┆ … ┆ 1    ┆ 0    ┆ 2     ┆ 0    │
│ MIR548J   ┆ 4    ┆ 14   ┆ 5     ┆ … ┆ 17   ┆ 6    ┆ 3     ┆ 7    │
│ MIR548V   ┆ 0    ┆ 0    ┆ 0     ┆ … ┆ 0    ┆ 3    ┆ 3     ┆ 0    │
└───────────┴──────┴──────┴───────┴───┴──────┴──────┴───────┴──────┘

In [51]:
te_counts_s

shape: (687, 67)
┌──────────┬─────────┬─────────┬─────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ TE       ┆ V888    ┆ V108    ┆ V2089   ┆ … ┆ V883    ┆ V655    ┆ V1699   ┆ V624    │
│ ---      ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ str      ┆ f64     ┆ f64     ┆ f64     ┆   ┆ f64     ┆ f64     ┆ f64     ┆ f64     │
╞══════════╪═════════╪═════════╪═════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ ALU      ┆ 9143.6  ┆ 8986.45 ┆ 10564.3 ┆ … ┆ 6081.12 ┆ 7078.72 ┆ 9072.45 ┆ 6690.64 │
│ AluJb    ┆ 34480.6 ┆ 27678.3 ┆ 25346.5 ┆ … ┆ 22348.0 ┆ 26045.3 ┆ 38196.9 ┆ 24140.9 │
│ AluJo    ┆ 4724.76 ┆ 2273.46 ┆ 101.421 ┆ … ┆ 3394.73 ┆ 3315.78 ┆ 4838.48 ┆ 3233.89 │
│ AluJr    ┆ 1567.68 ┆ 1141.14 ┆ 936.128 ┆ … ┆ 1015.1  ┆ 1299.6  ┆ 1818.89 ┆ 1000.22 │
│ AluJr4   ┆ 8494.22 ┆ 6722.98 ┆ 7226.66 ┆ … ┆ 5684.14 ┆ 6111.24 ┆ 9584.53 ┆ 6364.48 │
│ …        ┆ …       ┆ …       ┆ …       ┆ … ┆ …       ┆ …       ┆ …       ┆ …       │
│ X5A_LINE ┆ 5.0     ┆ 21.0    ┆ 5.0     ┆ … ┆ 8.0     ┆ 4.0     ┆ 7.0     ┆ 4.0     │
│ X5B_LINE ┆ 8.0     ┆ 7.0     ┆ 7.0     ┆ … ┆ 15.0    ┆ 6.0     ┆ 18.0    ┆ 6.0     │
│ X6A_LINE ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ … ┆ 0.0     ┆ 4.0     ┆ 0.0     ┆ 0.0     │
│ X6B_LINE ┆ 1.0     ┆ 7.0     ┆ 5.0     ┆ … ┆ 1.0     ┆ 12.0    ┆ 5.0     ┆ 5.0     │
│ X8_LINE  ┆ 1.0     ┆ 0.0     ┆ 0.0     ┆ … ┆ 0.0     ┆ 6.0     ┆ 2.0     ┆ 0.0     │
└──────────┴─────────┴─────────┴─────────┴───┴─────────┴─────────┴─────────┴─────────┘

In [53]:
pirna

shape: (219, 67)
┌────────────────┬───────┬─────┬──────┬───┬───────┬───────┬──────┬──────┐
│ piRNA          ┆ V1505 ┆ N83 ┆ V513 ┆ … ┆ V1528 ┆ V1874 ┆ V716 ┆ V359 │
│ ---            ┆ ---   ┆ --- ┆ ---  ┆   ┆ ---   ┆ ---   ┆ ---  ┆ ---  │
│ str            ┆ i64   ┆ i64 ┆ i64  ┆   ┆ i64   ┆ i64   ┆ i64  ┆ i64  │
╞════════════════╪═══════╪═════╪══════╪═══╪═══════╪═══════╪══════╪══════╡
│ hsa_piR_016899 ┆ 0     ┆ 0   ┆ 0    ┆ … ┆ 0     ┆ 0     ┆ 0    ┆ 0    │
│ hsa_piR_020391 ┆ 0     ┆ 0   ┆ 0    ┆ … ┆ 0     ┆ 24    ┆ 0    ┆ 18   │
│ hsa_piR_001840 ┆ 0     ┆ 0   ┆ 0    ┆ … ┆ 0     ┆ 0     ┆ 0    ┆ 0    │
│ hsa_piR_003239 ┆ 0     ┆ 0   ┆ 0    ┆ … ┆ 24    ┆ 0     ┆ 0    ┆ 0    │
│ hsa_piR_009903 ┆ 0     ┆ 0   ┆ 0    ┆ … ┆ 14    ┆ 0     ┆ 0    ┆ 0    │
│ …              ┆ …     ┆ …   ┆ …    ┆ … ┆ …     ┆ …     ┆ …    ┆ …    │
│ hsa_piR_020814 ┆ 193   ┆ 277 ┆ 114  ┆ … ┆ 144   ┆ 230   ┆ 93   ┆ 93   │
│ hsa_piR_020815 ┆ 389   ┆ 307 ┆ 365  ┆ … ┆ 329   ┆ 493   ┆ 555  ┆ 304  │
│ hsa_piR_020829 ┆ 1198  ┆ 823 ┆ 1118 ┆ … ┆ 1173  ┆ 1346  ┆ 215  ┆ 985  │
│ hsa_piR_021032 ┆ 276   ┆ 178 ┆ 259  ┆ … ┆ 199   ┆ 441   ┆ 207  ┆ 111  │
│ hsa_piR_021462 ┆ 397   ┆ 138 ┆ 253  ┆ … ┆ 235   ┆ 264   ┆ 103  ┆ 294  │
└────────────────┴───────┴─────┴──────┴───┴───────┴───────┴──────┴──────┘

In [54]:
skf = StratifiedKFold(n_splits=5)

omic='pirna'

for y, task in labels:
    for i, (train_idx, test_idx) in enumerate(skf.split(np.zeros(len(y)), y)):

        # print(train_idx.shape, test_idx.shape)
        # print(train_idx, test_idx)
        # print(np.unique(y[train_idx], return_counts=True))
        # print(np.unique(y[test_idx], return_counts=True))

        mrna_selected = mrmr_selection(
            X_df=pirna,
            y=y,
            train_mask=train_idx,
            n_features=200,
            n_preselected_features=None,
            feature_col_name="piRNA",
        )

        mrna_selected.write_csv(f"MDS_data_preprocessed/mrmr_selected/{task}/{omic}/{omic}_fold_{i}.csv")

100%|██████████| 200/200 [00:02<00:00, 71.38it/s]
100%|██████████| 200/200 [00:02<00:00, 70.84it/s]
100%|██████████| 200/200 [00:02<00:00, 71.41it/s]
100%|██████████| 200/200 [00:02<00:00, 71.51it/s]
100%|██████████| 200/200 [00:02<00:00, 72.04it/s]
100%|██████████| 200/200 [00:02<00:00, 72.83it/s]
100%|██████████| 200/200 [00:02<00:00, 73.31it/s]
100%|██████████| 200/200 [00:02<00:00, 73.08it/s]
100%|██████████| 200/200 [00:02<00:00, 73.82it/s]
100%|██████████| 200/200 [00:02<00:00, 72.98it/s]
100%|██████████| 200/200 [00:02<00:00, 71.41it/s]
100%|██████████| 200/200 [00:02<00:00, 74.81it/s]
100%|██████████| 200/200 [00:02<00:00, 73.03it/s]
100%|██████████| 200/200 [00:02<00:00, 72.74it/s]
100%|██████████| 200/200 [00:02<00:00, 71.30it/s]

In [4]:
mrna

shape: (19_873, 75)
┌──────────────┬───────┬───────┬───────┬───┬───────┬───────┬───────┬───────┐
│ GENE_NAME    ┆ V1884 ┆ N58   ┆ V630  ┆ … ┆ V806  ┆ V513  ┆ V1565 ┆ V1920 │
│ ---          ┆ ---   ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str          ┆ i64   ┆ i64   ┆ i64   ┆   ┆ i64   ┆ i64   ┆ i64   ┆ i64   │
╞══════════════╪═══════╪═══════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ RILPL1       ┆ 187   ┆ 235   ┆ 538   ┆ … ┆ 458   ┆ 263   ┆ 384   ┆ 649   │
│ RAB4B        ┆ 1296  ┆ 951   ┆ 1261  ┆ … ┆ 801   ┆ 989   ┆ 1682  ┆ 943   │
│ TIGAR        ┆ 1229  ┆ 184   ┆ 609   ┆ … ┆ 499   ┆ 400   ┆ 508   ┆ 204   │
│ DNAH3        ┆ 5     ┆ 0     ┆ 12    ┆ … ┆ 3     ┆ 0     ┆ 11    ┆ 22    │
│ RP11-432M8.3 ┆ 2     ┆ 1     ┆ 1     ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 3     │
│ …            ┆ …     ┆ …     ┆ …     ┆ … ┆ …     ┆ …     ┆ …     ┆ …     │
│ CYP4F2       ┆ 291   ┆ 182   ┆ 157   ┆ … ┆ 11    ┆ 127   ┆ 281   ┆ 225   │
│ TENM1        ┆ 131   ┆ 32    ┆ 16    ┆ … ┆ 19    ┆ 7     ┆ 49    ┆ 34    │
│ BATF3        ┆ 117   ┆ 67    ┆ 351   ┆ … ┆ 472   ┆ 74    ┆ 227   ┆ 39    │
│ PPP6R1       ┆ 24306 ┆ 28193 ┆ 23945 ┆ … ┆ 27759 ┆ 18774 ┆ 43097 ┆ 16402 │
│ OR8D4        ┆ 0     ┆ 0     ┆ 0     ┆ … ┆ 0     ┆ 0     ┆ 0     ┆ 34    │
└──────────────┴───────┴───────┴───────┴───┴───────┴───────┴───────┴───────┘

In [12]:
mrna.select(['GENE_NAME']+all_common_sample_names)

shape: (19_873, 67)
┌──────────────┬───────┬───────┬───────┬───┬───────┬───────┬───────┬───────┐
│ GENE_NAME    ┆ V888  ┆ V108  ┆ V2089 ┆ … ┆ V883  ┆ V655  ┆ V1699 ┆ V624  │
│ ---          ┆ ---   ┆ ---   ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---   ┆ ---   │
│ str          ┆ i64   ┆ i64   ┆ i64   ┆   ┆ i64   ┆ i64   ┆ i64   ┆ i64   │
╞══════════════╪═══════╪═══════╪═══════╪═══╪═══════╪═══════╪═══════╪═══════╡
│ RILPL1       ┆ 474   ┆ 60    ┆ 120   ┆ … ┆ 273   ┆ 131   ┆ 345   ┆ 164   │
│ RAB4B        ┆ 1130  ┆ 1080  ┆ 1798  ┆ … ┆ 887   ┆ 685   ┆ 2000  ┆ 1989  │
│ TIGAR        ┆ 362   ┆ 301   ┆ 511   ┆ … ┆ 328   ┆ 342   ┆ 793   ┆ 817   │
│ DNAH3        ┆ 19    ┆ 3     ┆ 12    ┆ … ┆ 0     ┆ 134   ┆ 33    ┆ 0     │
│ RP11-432M8.3 ┆ 2     ┆ 1     ┆ 0     ┆ … ┆ 4     ┆ 7     ┆ 3     ┆ 0     │
│ …            ┆ …     ┆ …     ┆ …     ┆ … ┆ …     ┆ …     ┆ …     ┆ …     │
│ CYP4F2       ┆ 84    ┆ 129   ┆ 22    ┆ … ┆ 152   ┆ 58    ┆ 62    ┆ 458   │
│ TENM1        ┆ 36    ┆ 173   ┆ 31    ┆ … ┆ 23    ┆ 777   ┆ 14    ┆ 4     │
│ BATF3        ┆ 131   ┆ 86    ┆ 104   ┆ … ┆ 137   ┆ 76    ┆ 100   ┆ 140   │
│ PPP6R1       ┆ 30607 ┆ 15464 ┆ 34875 ┆ … ┆ 23426 ┆ 14442 ┆ 32556 ┆ 27047 │
│ OR8D4        ┆ 3     ┆ 43    ┆ 0     ┆ … ┆ 0     ┆ 39    ┆ 3     ┆ 0     │
└──────────────┴───────┴───────┴───────┴───┴───────┴───────┴───────┴───────┘

In [25]:
# prepare pirnas too
# pirna = pl.read_excel("MDS_data/piRNA_counts.xlsx")

# pirna_samples = pirna.columns[1:]

# pirna_samples = [s.split("_")[0] for s in pirna_samples]

# common_samples_w_pirna = list(set(pirna_samples).intersection(set(sample_names)))

# annot_pi = annot.filter(pl.col("sample_ids").is_in(common_samples_w_pirna))

# pirna.columns = ['piRNA'] + pirna_samples
# pirna = pirna.select(['piRNA'] + common_samples_w_pirna)
# pirna_X = pirna.to_numpy()[:, 1:]
# pirna_zeros_mask = pirna_X.sum(axis=1) < 300
# pirna_zeros_idx = np.where(pirna_zeros_mask == False)[0]
# pirna_names = pirna['piRNA'].to_list()
# pirna_names = [name.split('/')[0] for name in pirna_names]
# pirna = pirna.with_columns(piRNA=pl.Series(pirna_names))
# pirna[pirna_zeros_idx].write_csv("MDS_data_preprocessed/pirna.csv")

shape: (556, 105)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ piRNA     ┆ V1565_S17 ┆ N58_S10-U ┆ V1874_S15 ┆ … ┆ V2147_S8- ┆ V2224_S19 ┆ V2089_S1- ┆ V788_S2- │
│ ---       ┆ -UMIs     ┆ MIs       ┆ -UMIs     ┆   ┆ UMIs      ┆ -UMIs     ┆ UMIs      ┆ UMIs     │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ i64       ┆ i64       ┆ i64       ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ hsa_piR_0 ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 06779/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ579258/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 07653/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ580430/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 09540/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ582872/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 00302/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ570363/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 0        │
│ 00390/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ570472/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ hsa_piR_0 ┆ 315       ┆ 274       ┆ 230       ┆ … ┆ 273       ┆ 161       ┆ 175       ┆ 43       │
│ 20814/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ598650/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 316       ┆ 458       ┆ 493       ┆ … ┆ 281       ┆ 574       ┆ 183       ┆ 120      │
│ 20815/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ598651/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 2732      ┆ 1064      ┆ 1346      ┆ … ┆ 749       ┆ 1192      ┆ 921       ┆ 391      │
│ 20829/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ598677/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 131       ┆ 177       ┆ 441       ┆ … ┆ 171       ┆ 398       ┆ 271       ┆ 217      │
│ 21032/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ598918/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ hsa_piR_0 ┆ 265       ┆ 188       ┆ 264       ┆ … ┆ 151       ┆ 311       ┆ 337       ┆ 161      │
│ 21462/gb/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ DQ599459/ ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Homo      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [69]:
y_d = annot['1 disease'].to_numpy()
y_r = annot['2 risk'].to_numpy()
y_m = annot['3 mutations (SF3B1only_wt)'].to_numpy()

np.unique(y_d, return_counts=True), np.unique(y_r, return_counts=True), np.unique(y_m, return_counts=True)

((array([1, 2]), array([13, 61])),
 (array([0, 1, 2]), array([21, 29, 24])),
 (array([0, 1, 2]), array([48, 14, 12])))

In [70]:
mrna_names = mrna.columns[1:]
mirna_names = mirna.columns[1:]
circrna_names = circrna.columns[1:]
te_names = te_counts.columns[1:]

y_d = annot['1 disease'].to_numpy()
y_r = annot['2 risk'].to_numpy()
y_m = annot['3 mutations (SF3B1only_wt)'].to_numpy()

y = y_m

annotated_samples_mask = y != 0

y = y - 1  # move to 0-indexing

In [71]:
y

array([-1, -1,  0, -1, -1, -1, -1, -1, -1,  1,  0, -1, -1, -1, -1, -1,  0,
       -1, -1, -1,  0, -1, -1,  0, -1,  1, -1,  0, -1, -1,  0, -1,  0,  1,
        0, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,  0, -1,  1,  0, -1,
        1,  1, -1,  1,  1, -1,  0, -1, -1, -1,  1, -1, -1, -1, -1,  0,  1,
       -1, -1,  1,  0, -1, -1])

In [63]:
mrna_X = mrna.to_numpy()[:, 1:].T
mirna_X = mirna.to_numpy()[:, 1:].T
circrna_X = circrna.to_numpy()[:, 1:].T
te_X = te_counts.to_numpy()[:, 1:].T

mrna_X = mrna_X[annotated_samples_mask]
mirna_X = mirna_X[annotated_samples_mask]
circrna_X = circrna_X[annotated_samples_mask]
te_X = te_X[annotated_samples_mask]

y = y[annotated_samples_mask]

print(np.unique(y, return_counts=True))

X = np.hstack([mrna_X]) #, mirna_X, circrna_X, te_X])

NameError: name 'annotated_samples_mask' is not defined

In [62]:
knn_eval(X, y, select_n_features=True, nn_range=(1, 15))

NameError: name 'X' is not defined

In [79]:
svm_eval(X, y, select_n_features=True, n_trials=15)

Trial 1 / 15
| SVM | 0.81 +/- 0.17 | 0.80 +/- 0.18 | 0.80 +/- 0.18 |
Trial 2 / 15
| SVM | 0.85 +/- 0.15 | 0.84 +/- 0.15 | 0.84 +/- 0.16 |
Trial 3 / 15
Trial 4 / 15
Trial 5 / 15
Trial 6 / 15
Trial 7 / 15
Trial 8 / 15
| SVM | 0.89 +/- 0.09 | 0.89 +/- 0.09 | 0.89 +/- 0.09 |
Trial 9 / 15
Trial 10 / 15
Trial 11 / 15
Trial 12 / 15
Trial 13 / 15
Trial 14 / 15
Trial 15 / 15
| LIN SVM | 0.89 +/- 0.09 | 0.89 +/- 0.09 | 0.89 +/- 0.09 |
study.best_value=0.8857142857142858, study.best_params={'C': 0.026365951353977148, 'class_weight': None, 'n_features': 518}

{'acc': 0.8866666666666667,
 'f1_macro': 0.8857142857142858,
 'f1_weighted': 0.8857142857142858,
 'acc_std': 0.09333333333333332,
 'f1_macro_std': 0.09389529557231419,
 'f1_weighted_std': 0.09389529557231416}

In [83]:
xgboost_eval(X, y, n_trials=1, norm_features=True)

0 / 25
ACC: [0.66666667 0.8        0.8        0.8        0.8       ]
F1M: [0.625      0.76190476 0.8        0.76190476 0.8       ]
F1W: [0.625      0.78095238 0.8        0.78095238 0.8       ]
 XGBoost val | 0.83 +/- 0.21 | 0.80 +/- 0.27 | 0.87 +/- 0.16 |
| XGBoost | 0.77 +/- 0.05 | 0.75 +/- 0.06 | 0.76 +/- 0.07 |
1 / 25
2 / 25
3 / 25
4 / 25
5 / 25
6 / 25
7 / 25
8 / 25
9 / 25
10 / 25
ACC: [1.  1.  0.6 1.  0.8]
F1M: [1.         1.         0.58333333 1.         0.8       ]
F1W: [1.  1.  0.6 1.  0.8]
 XGBoost val | 0.90 +/- 0.20 | 0.87 +/- 0.27 | 0.93 +/- 0.13 |
| XGBoost | 0.88 +/- 0.16 | 0.88 +/- 0.17 | 0.88 +/- 0.16 |
11 / 25
12 / 25
13 / 25
14 / 25
15 / 25
Pruning trial
16 / 25
ACC: [1.  1.  0.8 1.  0.8]
F1M: [1.         1.         0.76190476 1.         0.8       ]
F1W: [1.         1.         0.78095238 1.         0.8       ]
 XGBoost val | 0.90 +/- 0.20 | 0.87 +/- 0.27 | 0.93 +/- 0.13 |
| XGBoost | 0.92 +/- 0.10 | 0.91 +/- 0.11 | 0.92 +/- 0.10 |
17 / 25
18 / 25
19 / 25
20 / 25
21 / 25
22 / 25
23 / 25
24 / 25
| XGBoost | 0.92 +/- 0.10 | 0.91 +/- 0.11 | 0.92 +/- 0.10 |
study.best_value=0.9161904761904761, study.best_params={'booster': 'gblinear', 'lambda': 0.013581694072869377, 'alpha': 0.03128552626207971}

In [94]:
mlp_eval(X, y, reg_type=None, n_trials=15)

Trial 0 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
{'acc': 0.800000011920929, 'f1_macro': 0.7999999999999999, 'f1_weighted': 0.7999999999999999, 'acc_std': 0.16329930645214746, 'f1_macro_std': 0.16329931618554525, 'f1_weighted_std': 0.16329931618554525}
Trial 1 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
Trial 2 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
Trial 3 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
Trial 4 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
Trial 5 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 0.33333334 0.66666669]
[0.66666667 1.         0.66666667 0.25       0.66666667]
[0.66666667 1.         0.66666667 0.33333333 0.66666667]
Trial 6 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 0.         1.        ]
[0.66666667 1.         0.66666667 0.         1.        ]
[0.66666667 1.         0.66666667 0.         1.        ]
Trial 7 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 0.         1.        ]
[0.66666667 1.         0.66666667 0.         1.        ]
[0.66666667 1.         0.66666667 0.         1.        ]
Trial 8 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
Trial 9 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
Trial 10 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
Trial 11 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
Trial 12 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 0.33333334 0.66666669]
[0.66666667 1.         0.66666667 0.25       0.66666667]
[0.66666667 1.         0.66666667 0.33333333 0.66666667]
Trial 13 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
Trial 14 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
study.best_value=2.4000000119209286, study.best_params={'lr': 0.00019602853749566614, 'l1_lambda': 0.0008512581339605337, 'l2_lambda': 6.59819969212904e-05, 'proj_dim': 222, 'hidden_channels': 164, 'n_features': 2403}
| MLP regularization : None | 0.80 +/- 0.16 | 0.80 +/- 0.16 | 0.80 +/- 0.16 |

{'acc': 0.9, 'f1_macro': 0.7856410256410257, 'f1_weighted': 0.8851282051282052, 'acc_std': 0.09354143466934853, 'f1_macro_std': 0.20390403951541392, 'f1_weighted_std': 0.10002169389933914}

| MLP no regularization |  0.90 +- 0.09 |  0.79 +- 0.20 |  0.89 +- 0.10 |

In [95]:
mlp_eval(X, y, reg_type='l1', n_trials=13)

Trial 0 / 13
Eval 1 / 5
torch.Size([20, 572])
torch.Size([3, 572])
torch.Size([3, 572])
Eval 2 / 5
torch.Size([21, 572])
torch.Size([2, 572])
torch.Size([3, 572])
Eval 3 / 5
torch.Size([21, 572])
torch.Size([2, 572])
torch.Size([3, 572])
Eval 4 / 5
torch.Size([21, 572])
torch.Size([2, 572])
torch.Size([3, 572])
Eval 5 / 5
torch.Size([21, 572])
torch.Size([2, 572])
torch.Size([3, 572])
[0.66666669 1.         0.66666669 0.         1.        ]
[0.66666667 1.         0.66666667 0.         1.        ]
[0.66666667 1.         0.66666667 0.         1.        ]
{'acc': 0.6666666746139527, 'f1_macro': 0.6666666666666666, 'f1_weighted': 0.6666666666666666, 'acc_std': 0.3651483716701108, 'f1_macro_std': 0.36514837167011077, 'f1_weighted_std': 0.36514837167011077}
Trial 1 / 13
Eval 1 / 5
torch.Size([20, 2527])
torch.Size([3, 2527])
torch.Size([3, 2527])
Eval 2 / 5
torch.Size([21, 2527])
torch.Size([2, 2527])
torch.Size([3, 2527])
Eval 3 / 5
torch.Size([21, 2527])
torch.Size([2, 2527])
torch.Size([3, 2527])
Eval 4 / 5
torch.Size([21, 2527])
torch.Size([2, 2527])
torch.Size([3, 2527])
Eval 5 / 5
torch.Size([21, 2527])
torch.Size([2, 2527])
torch.Size([3, 2527])
[0.66666669 1.         0.66666669 0.33333334 1.        ]
[0.66666667 1.         0.66666667 0.25       1.        ]
[0.66666667 1.         0.66666667 0.33333333 1.        ]
{'acc': 0.7333333432674408, 'f1_macro': 0.7166666666666666, 'f1_weighted': 0.7333333333333333, 'acc_std': 0.24944382047492575, 'f1_macro_std': 0.27688746209726917, 'f1_weighted_std': 0.24944382578492943}
Trial 2 / 13
Eval 1 / 5
torch.Size([20, 2005])
torch.Size([3, 2005])
torch.Size([3, 2005])
Eval 2 / 5
torch.Size([21, 2005])
torch.Size([2, 2005])
torch.Size([3, 2005])
Eval 3 / 5
torch.Size([21, 2005])
torch.Size([2, 2005])
torch.Size([3, 2005])
Eval 4 / 5
torch.Size([21, 2005])
torch.Size([2, 2005])
torch.Size([3, 2005])
Eval 5 / 5
torch.Size([21, 2005])
torch.Size([2, 2005])
torch.Size([3, 2005])
[0.66666669 1.         0.66666669 1.         0.66666669]
[0.66666667 1.         0.66666667 1.         0.66666667]
[0.66666667 1.         0.66666667 1.         0.66666667]
{'acc': 0.800000011920929, 'f1_macro': 0.7999999999999999, 'f1_weighted': 0.7999999999999999, 'acc_std': 0.16329930645214746, 'f1_macro_std': 0.16329931618554525, 'f1_weighted_std': 0.16329931618554525}
Trial 3 / 13
Eval 1 / 5
torch.Size([20, 2563])
torch.Size([3, 2563])
torch.Size([3, 2563])
Eval 2 / 5
torch.Size([21, 2563])
torch.Size([2, 2563])
torch.Size([3, 2563])
Eval 3 / 5
torch.Size([21, 2563])
torch.Size([2, 2563])
torch.Size([3, 2563])
Eval 4 / 5
torch.Size([21, 2563])
torch.Size([2, 2563])
torch.Size([3, 2563])
Eval 5 / 5
torch.Size([21, 2563])
torch.Size([2, 2563])
torch.Size([3, 2563])
[0.66666669 1.         1.         0.         0.66666669]
[0.66666667 1.         1.         0.         0.66666667]
[0.66666667 1.         1.         0.         0.66666667]
Trial 4 / 13
Eval 1 / 5
torch.Size([20, 924])
torch.Size([3, 924])
torch.Size([3, 924])
Eval 2 / 5
torch.Size([21, 924])
torch.Size([2, 924])
torch.Size([3, 924])
Eval 3 / 5
torch.Size([21, 924])
torch.Size([2, 924])
torch.Size([3, 924])
Eval 4 / 5
torch.Size([21, 924])
torch.Size([2, 924])
torch.Size([3, 924])
Eval 5 / 5
torch.Size([21, 924])
torch.Size([2, 924])
torch.Size([3, 924])
[0.66666669 1.         0.66666669 0.66666669 0.66666669]
[0.66666667 1.         0.66666667 0.4        0.66666667]
[0.66666667 1.         0.66666667 0.53333333 0.66666667]
Trial 5 / 13
Eval 1 / 5
torch.Size([20, 2952])
torch.Size([3, 2952])
torch.Size([3, 2952])
Eval 2 / 5
torch.Size([21, 2952])
torch.Size([2, 2952])
torch.Size([3, 2952])
Eval 3 / 5
torch.Size([21, 2952])
torch.Size([2, 2952])
torch.Size([3, 2952])
Eval 4 / 5
torch.Size([21, 2952])
torch.Size([2, 2952])
torch.Size([3, 2952])
Eval 5 / 5
torch.Size([21, 2952])
torch.Size([2, 2952])
torch.Size([3, 2952])
[0.66666669 1.         0.66666669 0.66666669 0.66666669]
[0.66666667 1.         0.66666667 0.4        0.66666667]
[0.66666667 1.         0.66666667 0.53333333 0.66666667]
Trial 6 / 13
Eval 1 / 5
torch.Size([20, 2921])
torch.Size([3, 2921])
torch.Size([3, 2921])
Eval 2 / 5
torch.Size([21, 2921])
torch.Size([2, 2921])
torch.Size([3, 2921])
Eval 3 / 5
torch.Size([21, 2921])
torch.Size([2, 2921])
torch.Size([3, 2921])
Eval 4 / 5
torch.Size([21, 2921])
torch.Size([2, 2921])
torch.Size([3, 2921])
Eval 5 / 5
torch.Size([21, 2921])
torch.Size([2, 2921])
torch.Size([3, 2921])
[0.66666669 1.         0.66666669 0.         0.66666669]
[0.66666667 1.         0.66666667 0.         0.66666667]
[0.66666667 1.         0.66666667 0.         0.66666667]
Trial 7 / 13
Eval 1 / 5
torch.Size([20, 301])
torch.Size([3, 301])
torch.Size([3, 301])
Eval 2 / 5
torch.Size([21, 301])
torch.Size([2, 301])
torch.Size([3, 301])
Eval 3 / 5
torch.Size([21, 301])
torch.Size([2, 301])
torch.Size([3, 301])
Eval 4 / 5
torch.Size([21, 301])
torch.Size([2, 301])
torch.Size([3, 301])
Eval 5 / 5
torch.Size([21, 301])
torch.Size([2, 301])
torch.Size([3, 301])
[0.66666669 1.         0.66666669 0.33333334 0.66666669]
[0.66666667 1.         0.66666667 0.25       0.66666667]
[0.66666667 1.         0.66666667 0.33333333 0.66666667]
Trial 8 / 13
Eval 1 / 5
torch.Size([20, 1358])
torch.Size([3, 1358])
torch.Size([3, 1358])
Eval 2 / 5
torch.Size([21, 1358])
torch.Size([2, 1358])
torch.Size([3, 1358])
Eval 3 / 5
torch.Size([21, 1358])
torch.Size([2, 1358])
torch.Size([3, 1358])
Eval 4 / 5
torch.Size([21, 1358])
torch.Size([2, 1358])
torch.Size([3, 1358])
Eval 5 / 5
torch.Size([21, 1358])
torch.Size([2, 1358])
torch.Size([3, 1358])
[0.66666669 1.         0.66666669 0.33333334 0.66666669]
[0.66666667 1.         0.66666667 0.25       0.66666667]
[0.66666667 1.         0.66666667 0.33333333 0.66666667]
Trial 9 / 13
Eval 1 / 5
torch.Size([20, 471])
torch.Size([3, 471])
torch.Size([3, 471])
Eval 2 / 5
torch.Size([21, 471])
torch.Size([2, 471])
torch.Size([3, 471])
Eval 3 / 5
torch.Size([21, 471])
torch.Size([2, 471])
torch.Size([3, 471])
Eval 4 / 5
torch.Size([21, 471])
torch.Size([2, 471])
torch.Size([3, 471])
Eval 5 / 5
torch.Size([21, 471])
torch.Size([2, 471])
torch.Size([3, 471])
[0.66666669 1.         0.66666669 0.66666669 0.66666669]
[0.66666667 1.         0.66666667 0.4        0.66666667]
[0.66666667 1.         0.66666667 0.53333333 0.66666667]
Trial 10 / 13
Eval 1 / 5
torch.Size([20, 1898])
torch.Size([3, 1898])
torch.Size([3, 1898])
Eval 2 / 5
torch.Size([21, 1898])
torch.Size([2, 1898])
torch.Size([3, 1898])
Eval 3 / 5
torch.Size([21, 1898])
torch.Size([2, 1898])
torch.Size([3, 1898])
Eval 4 / 5
torch.Size([21, 1898])
torch.Size([2, 1898])
torch.Size([3, 1898])
Eval 5 / 5
torch.Size([21, 1898])
torch.Size([2, 1898])
torch.Size([3, 1898])
[0.66666669 1.         0.66666669 0.66666669 0.66666669]
[0.66666667 1.         0.66666667 0.4        0.66666667]
[0.66666667 1.         0.66666667 0.53333333 0.66666667]
Trial 11 / 13
Eval 1 / 5
torch.Size([20, 1992])
torch.Size([3, 1992])
torch.Size([3, 1992])
Eval 2 / 5
torch.Size([21, 1992])
torch.Size([2, 1992])
torch.Size([3, 1992])
Eval 3 / 5
torch.Size([21, 1992])
torch.Size([2, 1992])
torch.Size([3, 1992])
Eval 4 / 5
torch.Size([21, 1992])
torch.Size([2, 1992])
torch.Size([3, 1992])
Eval 5 / 5
torch.Size([21, 1992])
torch.Size([2, 1992])
torch.Size([3, 1992])
[0.66666669 1.         0.66666669 0.33333334 0.66666669]
[0.66666667 1.         0.66666667 0.25       0.66666667]
[0.66666667 1.         0.66666667 0.33333333 0.66666667]
Trial 12 / 13
Eval 1 / 5
torch.Size([20, 2275])
torch.Size([3, 2275])
torch.Size([3, 2275])
Eval 2 / 5
torch.Size([21, 2275])
torch.Size([2, 2275])
torch.Size([3, 2275])
Eval 3 / 5
torch.Size([21, 2275])
torch.Size([2, 2275])
torch.Size([3, 2275])
Eval 4 / 5
torch.Size([21, 2275])
torch.Size([2, 2275])
torch.Size([3, 2275])
Eval 5 / 5
torch.Size([21, 2275])
torch.Size([2, 2275])
torch.Size([3, 2275])
[0.66666669 1.         0.66666669 0.         0.66666669]
[0.66666667 1.         0.66666667 0.         0.66666667]
[0.66666667 1.         0.66666667 0.         0.66666667]
study.best_value=2.4000000119209286, study.best_params={'lr': 0.000711099315108959, 'l1_lambda': 0.00039737319598071404, 'l2_lambda': 1.5135591721617464e-05, 'proj_dim': 224, 'hidden_channels': 53, 'n_features': 2005}
| MLP regularization : l1 | 0.80 +/- 0.16 | 0.80 +/- 0.16 | 0.80 +/- 0.16 |

In [8]:
mlp_eval(X, y, reg_type='inner_mat', n_trials=13)

Trial 0 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83333331 0.66666669 0.66666669 0.60000002 0.60000002]
[0.82857143 0.625      0.66666667 0.58333333 0.58333333]
[0.82857143 0.625      0.66666667 0.56666667 0.6       ]
{'acc': 0.6733333468437195, 'f1_macro': 0.6573809523809523, 'f1_weighted': 0.6573809523809524, 'acc_std': 0.08537497357327423, 'f1_macro_std': 0.09100223016878, 'f1_weighted_std': 0.09161068172873033}
Trial 1 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
Pruning trial after 5 evals, cause 0.4714285714285714 < 0.6573809523809524
[0.66666669 0.5        0.5        0.40000001 0.80000001]
[0.66666667 0.33333333 0.48571429 0.4        0.76190476]
[0.66666667 0.33333333 0.48571429 0.4        0.78095238]
Trial 2 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83333331 0.5        0.66666669 0.60000002 0.80000001]
[0.82857143 0.33333333 0.66666667 0.58333333 0.76190476]
[0.82857143 0.33333333 0.66666667 0.56666667 0.78095238]
Trial 3 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83333331 0.66666669 0.66666669 0.40000001 0.80000001]
[0.82857143 0.625      0.66666667 0.4        0.76190476]
[0.82857143 0.625      0.66666667 0.4        0.78095238]
{'acc': 0.673333340883255, 'f1_macro': 0.6564285714285714, 'f1_weighted': 0.6602380952380952, 'acc_std': 0.15260697056057373, 'f1_macro_std': 0.14670144918419775, 'f1_weighted_std': 0.14960946894257363}
Trial 4 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83333331 0.66666669 0.5        0.60000002 0.80000001]
[0.82857143 0.625      0.48571429 0.58333333 0.76190476]
[0.82857143 0.625      0.48571429 0.56666667 0.78095238]
{'acc': 0.6800000071525574, 'f1_macro': 0.6569047619047619, 'f1_weighted': 0.6573809523809524, 'acc_std': 0.12400716214193236, 'f1_macro_std': 0.1234757405460739, 'f1_weighted_std': 0.12909154058395977}
Trial 5 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 0.66666669 0.66666669 0.60000002 0.80000001]
[0.66666667 0.625      0.66666667 0.58333333 0.76190476]
[0.66666667 0.625      0.66666667 0.56666667 0.78095238]
{'acc': 0.6800000190734863, 'f1_macro': 0.6607142857142856, 'f1_weighted': 0.6611904761904761, 'acc_std': 0.065319722580859, 'f1_macro_std': 0.059285236180898725, 'f1_weighted_std': 0.07021024468017387}
Trial 6 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
Pruning trial after 5 evals, cause 0.511904761904762 < 0.6611904761904761
[0.83333331 0.5        0.5        0.40000001 0.80000001]
[0.82857143 0.33333333 0.48571429 0.4        0.76190476]
[0.82857143 0.33333333 0.48571429 0.4        0.78095238]
Trial 7 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83333331 0.66666669 0.66666669 0.60000002 0.80000001]
[0.82857143 0.625      0.66666667 0.58333333 0.8       ]
[0.82857143 0.625      0.66666667 0.56666667 0.8       ]
{'acc': 0.7133333444595337, 'f1_macro': 0.7007142857142856, 'f1_weighted': 0.6973809523809523, 'acc_std': 0.0884433143840135, 'f1_macro_std': 0.09682487639724828, 'f1_weighted_std': 0.10100515242464879}
Trial 8 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83333331 0.5        0.66666669 0.60000002 0.60000002]
[0.82857143 0.33333333 0.66666667 0.58333333 0.58333333]
[0.82857143 0.33333333 0.66666667 0.56666667 0.6       ]
Trial 9 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83333331 0.66666669 0.66666669 0.60000002 0.60000002]
[0.82857143 0.625      0.66666667 0.58333333 0.58333333]
[0.82857143 0.625      0.66666667 0.56666667 0.56666667]
Trial 10 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 0.5        0.66666669 0.60000002 1.        ]
[0.66666667 0.33333333 0.66666667 0.58333333 1.        ]
[0.66666667 0.33333333 0.66666667 0.56666667 1.        ]
Trial 11 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 0.5        0.66666669 0.60000002 0.80000001]
[0.66666667 0.33333333 0.66666667 0.58333333 0.76190476]
[0.66666667 0.33333333 0.66666667 0.56666667 0.78095238]
Trial 12 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.66666669 0.5        0.66666669 0.60000002 0.60000002]
[0.66666667 0.33333333 0.66666667 0.58333333 0.375     ]
[0.66666667 0.33333333 0.66666667 0.56666667 0.45      ]
Trial 13 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83333331 0.66666669 0.66666669 0.60000002 0.60000002]
[0.82857143 0.625      0.66666667 0.58333333 0.58333333]
[0.82857143 0.625      0.66666667 0.56666667 0.6       ]
Trial 14 / 15
Eval 1 / 5
Eval 2 / 5
Eval 3 / 5
Eval 4 / 5
Eval 5 / 5
[0.83333331 0.66666669 0.66666669 0.60000002 0.80000001]
[0.82857143 0.625      0.66666667 0.58333333 0.76190476]
[0.82857143 0.625      0.66666667 0.56666667 0.78095238]
study.best_value=2.1114285825547716, study.best_params={'lr': 2.2476667482986343e-05, 'l1_lambda': 0.00016280619271432154, 'l2_lambda': 4.994301263549072e-05, 'proj_dim': 148, 'hidden_channels': 128, 'n_features': 2289}
| MLP regularization : inner_mat | 0.71 +/- 0.09 | 0.70 +/- 0.10 | 0.70 +/- 0.10 |

In [29]:
te_counts

shape: (687, 75)
┌──────────┬─────────┬─────────┬─────────┬───┬─────────┬─────────┬─────────┬─────────┐
│ TE       ┆ V1884   ┆ N58     ┆ V630    ┆ … ┆ V806    ┆ V513    ┆ V1565   ┆ V1920   │
│ ---      ┆ ---     ┆ ---     ┆ ---     ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ str      ┆ f64     ┆ f64     ┆ f64     ┆   ┆ f64     ┆ f64     ┆ f64     ┆ f64     │
╞══════════╪═════════╪═════════╪═════════╪═══╪═════════╪═════════╪═════════╪═════════╡
│ ALU      ┆ 13599.0 ┆ 7019.28 ┆ 6877.89 ┆ … ┆ 7599.44 ┆ 7370.1  ┆ 7059.21 ┆ 9787.8  │
│ AluJb    ┆ 44735.8 ┆ 26406.7 ┆ 24896.5 ┆ … ┆ 28709.9 ┆ 25891.1 ┆ 27218.6 ┆ 38261.4 │
│ AluJo    ┆ 4257.09 ┆ 4019.45 ┆ 2666.19 ┆ … ┆ 4184.29 ┆ 3155.55 ┆ 3744.24 ┆ 5137.53 │
│ AluJr    ┆ 1806.28 ┆ 1220.17 ┆ 1063.58 ┆ … ┆ 1238.01 ┆ 1206.32 ┆ 1180.33 ┆ 1694.92 │
│ AluJr4   ┆ 10841.0 ┆ 6707.35 ┆ 6414.47 ┆ … ┆ 7286.93 ┆ 6622.88 ┆ 7417.67 ┆ 9023.09 │
│ …        ┆ …       ┆ …       ┆ …       ┆ … ┆ …       ┆ …       ┆ …       ┆ …       │
│ X5A_LINE ┆ 3.0     ┆ 4.0     ┆ 4.0     ┆ … ┆ 8.0     ┆ 14.0    ┆ 2.0     ┆ 11.0    │
│ X5B_LINE ┆ 5.0     ┆ 8.0     ┆ 8.0     ┆ … ┆ 14.0    ┆ 7.0     ┆ 8.0     ┆ 1.0     │
│ X6A_LINE ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ 2.0     │
│ X6B_LINE ┆ 0.0     ┆ 0.0     ┆ 1.0     ┆ … ┆ 5.0     ┆ 14.0    ┆ 2.0     ┆ 0.0     │
│ X8_LINE  ┆ 0.0     ┆ 1.0     ┆ 0.0     ┆ … ┆ 0.0     ┆ 0.0     ┆ 0.0     ┆ 1.0     │
└──────────┴─────────┴─────────┴─────────┴───┴─────────┴─────────┴─────────┴─────────┘

In [91]:
val, test = mogonet_eval(
    input_omics={
        "mrna": mrna,
        # "mirna": mirna,
        # "circrna": circrna,
        # "te_counts": te_counts,
    },
    n_input_features={
        "mrna": 1000,
        # "mirna": 1000,
        # "circrna": 60,
        # "te_counts": 300,
    },
    y=y,
    params={
        "encoder_hidden_channels": {
            "mrna": 300,
            # "circrna": 50,
            # "mirna": 150,
            # "te_counts": 75,
        },
        "encoder_type": "gcn",
        "num_classes": 2,
        "graph_style": "threshold",
        "avg_degree": 15,
        # "graph_style": "knn",
        # "knn": 15,
        "dropout": 0.0,
        "epochs": 400,
        "log_interval": 50,
        "save_best_model": False,
        "integrator_type": "vcdn",
        "integration_dim": 2,
    }
)

dict_keys(['mrna'])
Fold 1 / 5
Building graph for mrna
0.75 tensor(58.5946)
0.875 tensor(22.7838)
0.9375 tensor(1.7838)
0.90625 tensor(10.0541)
0.890625 tensor(16.6757)
0.8984375 tensor(13.2432)
0.89453125 tensor(14.8649)
Isolated samples = 15, avg degree = 14.86486530303955
Epoch: 050:
Train Loss: 0.4031, Train Acc: 0.8000, Train F1 Macro: 0.7980, Train F1 Weighted: 0.8000
Val Loss: 0.2493, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 0.5027, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 100:
Train Loss: 0.3316, Train Acc: 0.8500, Train F1 Macro: 0.8400, Train F1 Weighted: 0.8440
Val Loss: 0.2688, Val Acc: 0.6667, Val F1 Macro: 0.6667, Val F1 Weighted: 0.6667
Test Loss: 0.4153, Test Acc: 1.0000, Test F1 Macro: 1.0000, Test F1 Weighted: 1.0000
##################################################
Epoch: 150:
Train Loss: 0.2798, Train Acc: 0.8500, Train F1 Macro: 0.8496, Train F1 Weighted: 0.8504
Val Loss: 0.1250, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 0.5529, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 200:
Train Loss: 0.2760, Train Acc: 0.8500, Train F1 Macro: 0.8496, Train F1 Weighted: 0.8504
Val Loss: 0.1207, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 0.5573, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 250:
Train Loss: 0.2752, Train Acc: 0.8500, Train F1 Macro: 0.8496, Train F1 Weighted: 0.8504
Val Loss: 0.1196, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 0.5586, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 300:
Train Loss: 0.2745, Train Acc: 0.8500, Train F1 Macro: 0.8496, Train F1 Weighted: 0.8504
Val Loss: 0.1188, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 0.5597, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 350:
Train Loss: 0.2738, Train Acc: 0.8500, Train F1 Macro: 0.8496, Train F1 Weighted: 0.8504
Val Loss: 0.1178, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 0.5608, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 400:
Train Loss: 0.2730, Train Acc: 0.8500, Train F1 Macro: 0.8496, Train F1 Weighted: 0.8504
Val Loss: 0.1168, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 0.5621, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Fold 2 / 5
Building graph for mrna
0.75 tensor(53.8919)
0.875 tensor(15.8919)
0.9375 tensor(0.8108)
0.90625 tensor(5.4865)
0.890625 tensor(10.4865)
0.8828125 tensor(13.1622)
0.87890625 tensor(14.3784)
0.876953125 tensor(15.1892)
Isolated samples = 12, avg degree = 15.189188957214355
Epoch: 050:
Train Loss: 0.3965, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8069
Val Loss: 0.3212, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 0.6742, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 100:
Train Loss: 0.3071, Train Acc: 0.8095, Train F1 Macro: 0.8091, Train F1 Weighted: 0.8095
Val Loss: 0.1262, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 1.3860, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.1667
##################################################
Epoch: 150:
Train Loss: 0.2903, Train Acc: 0.8095, Train F1 Macro: 0.8091, Train F1 Weighted: 0.8095
Val Loss: 0.0526, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 1.6872, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.1667
##################################################
Epoch: 200:
Train Loss: 0.2726, Train Acc: 0.8095, Train F1 Macro: 0.8091, Train F1 Weighted: 0.8095
Val Loss: 0.0387, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 1.9396, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.1667
##################################################
Epoch: 250:
Train Loss: 0.2641, Train Acc: 0.8095, Train F1 Macro: 0.8091, Train F1 Weighted: 0.8095
Val Loss: 0.0306, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 2.0420, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.1667
##################################################
Epoch: 300:
Train Loss: 0.2558, Train Acc: 0.8095, Train F1 Macro: 0.8091, Train F1 Weighted: 0.8095
Val Loss: 0.0230, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 2.2681, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.1667
##################################################
Epoch: 350:
Train Loss: 0.2464, Train Acc: 0.8571, Train F1 Macro: 0.8558, Train F1 Weighted: 0.8565
Val Loss: 0.0203, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 2.1887, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.1667
##################################################
Epoch: 400:
Train Loss: 0.2462, Train Acc: 0.8571, Train F1 Macro: 0.8571, Train F1 Weighted: 0.8571
Val Loss: 0.0180, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 2.0953, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.1667
##################################################
Fold 3 / 5
Building graph for mrna
0.75 tensor(60.9189)
0.875 tensor(26.7838)
0.9375 tensor(2.6757)
0.90625 tensor(13.3784)
0.890625 tensor(20.4865)
0.8984375 tensor(16.7568)
0.90234375 tensor(14.9189)
Isolated samples = 17, avg degree = 14.91891860961914
Epoch: 050:
Train Loss: 0.4751, Train Acc: 0.7619, Train F1 Macro: 0.7619, Train F1 Weighted: 0.7619
Val Loss: 0.5037, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 0.6197, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 100:
Train Loss: 0.3825, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8069
Val Loss: 0.4598, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 1.0522, Test Acc: 0.0000, Test F1 Macro: 0.0000, Test F1 Weighted: 0.0000
##################################################
Epoch: 150:
Train Loss: 0.3740, Train Acc: 0.8571, Train F1 Macro: 0.8518, Train F1 Weighted: 0.8531
Val Loss: 0.4940, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 1.1735, Test Acc: 0.0000, Test F1 Macro: 0.0000, Test F1 Weighted: 0.0000
##################################################
Epoch: 200:
Train Loss: 0.3729, Train Acc: 0.8571, Train F1 Macro: 0.8518, Train F1 Weighted: 0.8531
Val Loss: 0.4984, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 1.1841, Test Acc: 0.0000, Test F1 Macro: 0.0000, Test F1 Weighted: 0.0000
##################################################
Epoch: 250:
Train Loss: 0.3724, Train Acc: 0.8571, Train F1 Macro: 0.8518, Train F1 Weighted: 0.8531
Val Loss: 0.5008, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 1.1893, Test Acc: 0.0000, Test F1 Macro: 0.0000, Test F1 Weighted: 0.0000
##################################################
Epoch: 300:
Train Loss: 0.3718, Train Acc: 0.8571, Train F1 Macro: 0.8518, Train F1 Weighted: 0.8531
Val Loss: 0.5034, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 1.1947, Test Acc: 0.0000, Test F1 Macro: 0.0000, Test F1 Weighted: 0.0000
##################################################
Epoch: 350:
Train Loss: 0.3712, Train Acc: 0.8571, Train F1 Macro: 0.8518, Train F1 Weighted: 0.8531
Val Loss: 0.5062, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 1.2003, Test Acc: 0.0000, Test F1 Macro: 0.0000, Test F1 Weighted: 0.0000
##################################################
Epoch: 400:
Train Loss: 0.3706, Train Acc: 0.8571, Train F1 Macro: 0.8518, Train F1 Weighted: 0.8531
Val Loss: 0.5090, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 1.2058, Test Acc: 0.0000, Test F1 Macro: 0.0000, Test F1 Weighted: 0.0000
##################################################
Fold 4 / 5
Building graph for mrna
0.75 tensor(36.8108)
0.875 tensor(6.2703)
0.8125 tensor(21.9459)
0.84375 tensor(13.5946)
0.828125 tensor(17.7297)
0.8359375 tensor(15.5676)
0.83984375 tensor(14.6486)
Isolated samples = 15, avg degree = 14.648648262023926
Epoch: 050:
Train Loss: 0.3522, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8069
Val Loss: 1.5144, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 0.9325, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.3333
##################################################
Epoch: 100:
Train Loss: 0.3489, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8069
Val Loss: 1.4941, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 0.9384, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.3333
##################################################
Epoch: 150:
Train Loss: 0.3482, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8069
Val Loss: 1.4919, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 0.9381, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.3333
##################################################
Epoch: 200:
Train Loss: 0.3475, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8069
Val Loss: 1.4897, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 0.9375, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.3333
##################################################
Epoch: 250:
Train Loss: 0.3468, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8069
Val Loss: 1.4874, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 0.9370, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.3333
##################################################
Epoch: 300:
Train Loss: 0.3460, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8069
Val Loss: 1.4845, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 0.9368, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.3333
##################################################
Epoch: 350:
Train Loss: 0.3451, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8069
Val Loss: 1.4819, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 0.9363, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.3333
##################################################
Epoch: 400:
Train Loss: 0.3442, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8069
Val Loss: 1.4792, Val Acc: 0.5000, Val F1 Macro: 0.3333, Val F1 Weighted: 0.3333
Test Loss: 0.9356, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.3333
##################################################
Fold 5 / 5
Building graph for mrna
0.75 tensor(52.8649)
0.875 tensor(13.7838)
0.8125 tensor(35.1892)
0.84375 tensor(24.4595)
0.859375 tensor(19.7568)
0.8671875 tensor(16.7838)
0.87109375 tensor(14.8919)
Isolated samples = 11, avg degree = 14.891891479492188
Epoch: 050:
Train Loss: 0.3672, Train Acc: 0.8571, Train F1 Macro: 0.8444, Train F1 Weighted: 0.8508
Val Loss: 0.3655, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 0.9898, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.1667
##################################################
Epoch: 100:
Train Loss: 0.2820, Train Acc: 0.8571, Train F1 Macro: 0.8558, Train F1 Weighted: 0.8578
Val Loss: 0.3019, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 1.3889, Test Acc: 0.3333, Test F1 Macro: 0.2500, Test F1 Weighted: 0.1667
##################################################
Epoch: 150:
Train Loss: 0.2563, Train Acc: 0.8571, Train F1 Macro: 0.8558, Train F1 Weighted: 0.8578
Val Loss: 0.2856, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 1.2609, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 200:
Train Loss: 0.2509, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8095
Val Loss: 0.2999, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 1.2932, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 250:
Train Loss: 0.2502, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8095
Val Loss: 0.3017, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 1.2968, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 300:
Train Loss: 0.2499, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8095
Val Loss: 0.3026, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 1.2983, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 350:
Train Loss: 0.2495, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8095
Val Loss: 0.3036, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 1.3001, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################
Epoch: 400:
Train Loss: 0.2491, Train Acc: 0.8095, Train F1 Macro: 0.8056, Train F1 Weighted: 0.8095
Val Loss: 0.3047, Val Acc: 1.0000, Val F1 Macro: 1.0000, Val F1 Weighted: 1.0000
Test Loss: 1.3022, Test Acc: 0.6667, Test F1 Macro: 0.6667, Test F1 Weighted: 0.6667
##################################################

In [72]:
val, test

NameError: name 'val' is not defined

In [93]:
print("MOGONET GCN (mrna only) results:")
print(f"| MOGONET GCN (mrna only) val | {val[:, 0].mean():.2f} +/- {val[:, 0].std():.2f} | {val[:, 1].mean():.2f} +/- {val[:, 1].std():.2f} | {val[:, 2].mean():.2f} +/- {val[:, 2].std():.2f} |")
print(f"| MOGONET GCN (mrna only) test | {test[:, 0].mean():.2f} +/- {test[:, 0].std():.2f} | {test[:, 1].mean():.2f} +/- {test[:, 1].std():.2f} | {test[:, 2].mean():.2f} +/- {test[:, 2].std():.2f} |")

MOGONET GCN (mrna only) results:
| MOGONET GCN (mrna only) val | 0.83 +/- 0.24 | 0.80 +/- 0.30 | 0.80 +/- 0.30 |
| MOGONET GCN (mrna only) test | 0.73 +/- 0.15 | 0.73 +/- 0.15 | 0.73 +/- 0.15 |

In [89]:
print("MOGONET GAT (mrna only) results:")
print(f"| MOGONET GAT (mrna only) val | {val[:, 0].mean():.2f} +/- {val[:, 0].std():.2f} | {val[:, 1].mean():.2f} +/- {val[:, 1].std():.2f} | {val[:, 2].mean():.2f} +/- {val[:, 2].std():.2f} |")
print(f"| MOGONET GAT (mrna only) test | {test[:, 0].mean():.2f} +/- {test[:, 0].std():.2f} | {test[:, 1].mean():.2f} +/- {test[:, 1].std():.2f} | {test[:, 2].mean():.2f} +/- {test[:, 2].std():.2f} |")

MOGONET GAT (mrna only) results:
| MOGONET GAT (mrna only) val | 1.00 +/- 0.00 | 1.00 +/- 0.00 | 1.00 +/- 0.00 |
| MOGONET GAT (mrna only) test | 0.53 +/- 0.38 | 0.52 +/- 0.39 | 0.53 +/- 0.38 |

# DISEASE

## mrna only
| Model | Accuracy | F1 macro | F1 weighted |
| --- | --- | --- | --- |
| KNN | 0.91 +/- 0.08 | 0.76 +/- 0.21 | 0.89 +/- 0.10 |
| LIN SVM | 0.85 +/- 0.11 | 0.79 +/- 0.11 | 0.86 +/- 0.09 |
| XGBoost | 0.93 +/- 0.06 | 0.89 +/- 0.09 | 0.94 +/- 0.06 |
| MLP no regularization | 0.90 +/- 0.09 | 0.79 +/- 0.20 | 0.89 +/- 0.10 |
| MLP l1 regularization | 0.90 +/- 0.09 | 0.79 +/- 0.20 | 0.89 +/- 0.10 |
| MLP inner mat | 0.90 +/- 0.09 | 0.79 +/- 0.20 | 0.89 +/- 0.10 |
| MOGONET GCN (mrna only) | 0.82 +/- 0.12 | 0.76 +/- 0.15 | 0.83 +/- 0.10 |
| MOGONET GAT (mrna only) | 0.93 +/- 0.07 | 0.89 +/- 0.10 | 0.93 +/- 0.07 |
| Bipartite GNN (mrna only) | 0.94 +/- 0.08 | 0.92 +/- 0.12 | 0.95 +/- 0.07 |

## all

# RISK

## mrna only
| KNN | 0.89 +/- 0.11 | 0.75 +/- 0.26 | 0.88 +/- 0.13 |
| LIN SVM | 0.88 +/- 0.11 | 0.84 +/- 0.12 | 0.89 +/- 0.10 |
| XGBoost | 0.93 +/- 0.04 | 0.89 +/- 0.07 | 0.93 +/- 0.04 |
| MLP no regularization |  0.90 +- 0.09 |  0.79 +- 0.20 |  0.89 +- 0.10 |
| MLP regularization : l1 | 0.71 +/- 0.17 | 0.67 +/- 0.21 | 0.69 +/- 0.19 |
| MLP regularization : inner_mat | 0.71 +/- 0.09 | 0.70 +/- 0.10 | 0.70 +/- 0.10 |
| MOGONET GCN (mrna only) test | 0.64 +/- 0.15 | 0.61 +/- 0.19 | 0.60 +/- 0.21 |
| MOGONET GAT (mrna only) test | 0.71 +/- 0.10 | 0.71 +/- 0.10 | 0.71 +/- 0.10 |

## all
| KNN | 0.70 +/- 0.15 | 0.65 +/- 0.20 | 0.66 +/- 0.19 |
| LIN SVM | 0.72 +/- 0.12 | 0.70 +/- 0.13 | 0.71 +/- 0.13 |
| XGBoost | 0.66 +/- 0.07 | 0.63 +/- 0.07 | 0.64 +/- 0.07 |
| MLP regularization : None | 0.71 +/- 0.09 | 0.69 +/- 0.09 | 0.69 +/- 0.10 |
| MLP regularization : l1 | 0.71 +/- 0.09 | 0.70 +/- 0.10 | 0.70 +/- 0.10 |
| MLP regularization : inner_mat | 0.71 +/- 0.09 | 0.70 +/- 0.10 | 0.70 +/- 0.10 |
| MOGONET GAT (mrna only) test | 0.71 +/- 0.10 | 0.71 +/- 0.10 | 0.71 +/- 0.10 |

# MUTATION

| KNN | 0.79 +/- 0.24 | 0.78 +/- 0.24 | 0.78 +/- 0.24 |
| LIN SVM | 0.89 +/- 0.09 | 0.89 +/- 0.09 | 0.89 +/- 0.09 |
| XGBoost | 0.92 +/- 0.10 | 0.91 +/- 0.11 | 0.92 +/- 0.10 |
| MLP regularization : None | 0.80 +/- 0.16 | 0.80 +/- 0.16 | 0.80 +/- 0.16 |